/*     */ package xyz.pixelatedw.mineminenomi.init;
/*     */ 
/*     */ import java.util.Arrays;
/*     */ import java.util.Objects;
/*     */ import net.minecraftforge.eventbus.api.IEventBus;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.BakudanAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.BattoStrikeAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.BellyFlopAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.BombThrowAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.ChargedCleaveAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.CommandAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.EmptyHandsAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.ExplosionImmunityAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.GrabLockAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.GunArrayAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.HandcuffsImmunityAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.HeatImmunityAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.HonkAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.HookGrabAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.KnockdownAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.LeapAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.LogiaHeatImmunityAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.LogiaImmunityAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.MH5Ability;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.NegativeImmunityAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.NoFallDamageAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.OneTwoJangoAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.PearlFireAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.PoisonImmunityAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.ShakushiAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.SlamAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.SlashDamageImmunityAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.StealPunchAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.StealthFootAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.TailSpinAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.TakedownKickAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.Test2Ability;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.Test3Ability;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.TestAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.WeaponSpinAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.WeaponThrowAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.WootzNetLauncherAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.ZoomAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.artofweather.CoolBallAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.artofweather.GustSwordAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.artofweather.HeatBallAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.artofweather.ThunderBallAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.artofweather.WeatherEggAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.artofweather.tempos.CycloneTempo;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.artofweather.tempos.FogTempo;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.artofweather.tempos.HeatEggTempo;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.artofweather.tempos.MirageTempo;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.artofweather.tempos.RainTempo;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.artofweather.tempos.ThunderLanceTempo;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.artofweather.tempos.ThunderboltTempo;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.artofweather.tempos.ThunderstormTempo;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.artofweather.tempos.WeatherCloudTempo;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.awa.GoldenHourAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.awa.RelaxHourAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.awa.SoapDefenseAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.baku.BakuFactoryAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.baku.BakuMunchAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.baku.BakuTsuihoAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.baku.BeroCannonAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.bane.SpringDeathKnockAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.bane.SpringHopperAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.bane.SpringSnipeAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.bara.BaraBaraCarAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.bara.BaraBaraFestivalAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.bara.BaraBaraHoAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.bara.BaraSplitAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.bara.KuchuKirimomiDaiCircusAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.bari.BariBariNoPistolAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.bari.BarrierAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.bari.BarrierBallAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.bari.BarrierCrashAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.bari.BarrierbilityBatAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.bari.BarrierbilityStairsAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.beta.BetaBetaChainAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.beta.BetaCoatingAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.beta.BetaImmunityAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.beta.BetaLauncherAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.beta.HanamizuShinkenAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.blackleg.AntiMannerKickCourseAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.blackleg.BienCuitGrillShotAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.blackleg.BlackLegPassiveBonusesAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.blackleg.ConcasseAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.blackleg.DiableJambeAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.blackleg.ExtraHachisAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.blackleg.PartyTableKickCourseAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.blackleg.SkywalkAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.bomu.BreezeBreathBombAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.bomu.ExplosivePunchAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.bomu.KickBombAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.bomu.NoseFancyCannonAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.bomu.ZenshinKibakuAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.brawler.BrawlerPassiveBonusesAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.brawler.ChargedPunchAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.brawler.DamageAbsorptionAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.brawler.GenkotsuMeteorAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.brawler.HakaiHoAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.brawler.JishinHoAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.brawler.KingPunchAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.brawler.PunchRushAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.brawler.RyuNoIbukiAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.brawler.RyuNoKagizumeAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.brawler.SpinningBrawlAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.brawler.SuplexAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.brawler.TackleAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.carnivaltricks.IchirinZashiAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.carnivaltricks.KajiOyajiAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.carnivaltricks.KamikazeHyakkomaGekijoAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.chiyu.ChiyupopoAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.chiyu.HealingTouchAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.chiyu.KenpopoAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.chiyu.TearsAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.cyborg.ColaBackpackBonusAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.cyborg.ColaFuelAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.cyborg.ColaOverdriveAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.cyborg.CoupDeBooAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.cyborg.CoupDeVentAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.cyborg.CyborgPassiveBonusesAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.cyborg.FreshFireAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.cyborg.RadicalBeamAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.cyborg.SouthlandSuplexAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.cyborg.StrongRightAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.doa.AirDoorAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.doa.DoorDoorAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.doa.KaitenDoorAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.doctor.AntidoteShotAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.doctor.DopingAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.doctor.FailedExperimentAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.doctor.FirstAidAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.doctor.MedicBagExplosionAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.doctor.VirusZoneAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.doku.ChloroBallAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.doku.DokuFuguAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.doku.DokuGumoAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.doku.HydraAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.doku.VenomDemonAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.doku.VenomRoadAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.doru.CandleChampionAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.doru.CandleHouseAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.doru.CandleLockAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.doru.CandleWallAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.doru.DoruDoruArtsKenAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.doru.DoruDoruArtsMoriAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.doru.DoruDoruArtsPickaxeAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.doru.DoruDoruBallAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.doru.DoruDoruNoYakataAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.doru.TokudaiCandleAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.electro.EleclawAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.electro.ElectricalLunaAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.electro.ElectricalMissileAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.electro.ElectricalShowerAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.electro.ElectricalTempestaAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.electro.MinkPassiveBonusesAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.electro.SulongAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.electro.SulongCheckAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.fishmankarate.FishmanPassiveBonusesAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.fishmankarate.KachiageHaisokuAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.fishmankarate.KarakusagawaraSeikenAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.fishmankarate.MizuOsuAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.fishmankarate.MizuShuryudanAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.fishmankarate.MizuTaihoAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.fishmankarate.MurasameAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.fishmankarate.SamehadaShoteiAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.fishmankarate.SharkOnToothAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.fishmankarate.TwoFishEngineAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.fishmankarate.UchimizuAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.fishmankarate.YarinamiAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.gasu.BlueSwordAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.gasu.GasRobeAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.gasu.GastanetAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.gasu.GastilleAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.gasu.GasuFlyAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.gasu.GasuImmunityAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.gasu.GasuLogiaAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.gasu.KarakuniAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.gasu.KoroAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.gasu.ShinokuniAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.goe.DragonsRoarAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.goe.TodorokiAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.gomu.BouncyAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.gomu.GearFifthAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.gomu.GearFourthAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.gomu.GearFourthFlightAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.gomu.GearSecondAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.gomu.GearThirdAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.gomu.GomuGomuNoBazookaAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.gomu.GomuGomuNoDawnWhipAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.gomu.GomuGomuNoGatlingAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.gomu.GomuGomuNoGigantAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.gomu.GomuGomuNoPistolAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.gomu.GomuGomuNoRocketAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.goro.ElThorAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.goro.GoroLogiaAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.goro.GoroTravelAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.goro.KariAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.goro.RaigoAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.goro.SangoAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.goro.SparkStepAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.goro.VariAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.goro.VoltAmaruAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.goro.VoltAmaruFlightAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.gura.GekishinAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.gura.GuraImmunityAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.gura.KabutowariAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.gura.ShimaYurashiAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.gura.ShingenNoIchigekiAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.gura.TenchiMeidoAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.haki.BusoshokuHakiEmissionAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.haki.BusoshokuHakiFullBodyHardeningAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.haki.BusoshokuHakiHardeningAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.haki.BusoshokuHakiImbuingAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.haki.BusoshokuHakiInternalDestructionAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.haki.HaoshokuHakiAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.haki.HaoshokuHakiInfusionAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.haki.KenbunshokuHakiAuraAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.haki.KenbunshokuHakiFutureSightAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.hana.CampoDeFloresAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.hana.CienFleurStompAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.hana.CienFleurWingAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.hana.DosFleurClutchAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.hana.MilFleurAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.hana.SeisFleurSlapAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.hana.SeisFleurTwistAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.hana.VeinteFleurCalendulaAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.hie.FrostWalkerAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.hie.HieImmunityAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.hie.HieLogiaAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.hie.HieTravelAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.hie.IceAgeAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.hie.IceBallAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.hie.IceBlockAvalancheAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.hie.IceBlockPartisanAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.hie.IceBlockPheasantAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.hie.IceSaberAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.hie.IceTimeAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.hiso.AnimalFriendAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.hiso.ForewarnAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.hiso.LookoutAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.hitodaibutsu.HitoDaibutsuPointAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.hitodaibutsu.ImpactBlastAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.horo.MiniHollowAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.horo.NegativeHollowAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.horo.TokuHollowAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.horo.YutaiRidatsuAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.horu.ChiyuHormoneAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.horu.DeathWinkAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.horu.GanmenSeichoHormoneAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.horu.OnnaHormoneAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.horu.TensionHormoneAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.ito.BlackKnightAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.ito.FullbrightAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.ito.KumoNoSugakiAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.ito.OverheatAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.ito.ParasiteAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.ito.SoraNoMichiAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.ito.TamaitoAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.ito.TorikagoAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.jiki.AttractAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.jiki.DamnedPunkAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.jiki.GenocideRaidAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.jiki.MagneticItemsAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.jiki.PunkCornaDioAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.jiki.PunkCrossAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.jiki.PunkGibsonAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.jiki.PunkPistolsAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.jiki.RepelAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.kachi.EvaporateAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.kachi.HotBoilingSpecialAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.kachi.VulcanizationAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.kage.BlackBoxAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.kage.BrickBatAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.kage.DoppelmanAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.kage.KageGiriAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.kage.KageKakumeiAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.kage.KagemushaAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.kage.NightmareSoldiersAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.kage.ShadowsAsgardAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.kage.TsunoTokageAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.kame.KameGuardPointAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.kame.KameRideableAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.kame.KameWalkPointAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.karu.IngaZarashiAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.karu.KarmaAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.kilo.KiloPress10000Ability;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.kilo.KiloPress1Ability;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.kilo.KiloPunch5000Ability;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.kira.BrilliantPunkAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.kira.CabochonKnuckleAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.kira.DiamondBodyAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.kobu.ShoureiAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.kuku.GastronomorphAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.kuku.GourmetSnipeAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.kuku.GourmetamorphosisAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.magu.BakuretsuKazanAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.magu.DaiFunkaAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.magu.LavaFlowAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.magu.MagmaCoatingAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.magu.MaguLogiaAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.magu.MeigoAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.magu.RyuseiKazanAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.mandemontactics.DemonicDanceAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.mandemontactics.DemonicDashAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.mandemontactics.DemonicSmashAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.mane.ManeManeMemoryAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.marineloyalty.MusterAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.marineloyalty.SmallMusterAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.mega.DekaDekaAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.mega.DekaTrampleAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.mera.DaiEnkaiAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.mera.HeatDashAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.mera.HibashiraAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.mera.HidarumaAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.mera.HiganAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.mera.HikenAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.mera.JujikaAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.mera.KyokaenAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.mera.MeraLogiaAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.mero.MeroMeroMellowAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.mero.PerfumeFemurAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.mero.PistolKissAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.mero.SlaveArrowAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.mini.MiniMiniAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.mini.PaperFloatAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.mogu.MoguHeavyPointAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.mogu.MoguraBananaAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.mogu.MoguraTonpoAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.moku.MokuFlyAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.moku.MokuImmunityAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.moku.MokuLogiaAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.moku.SmokeLaunchAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.moku.WhiteBlowAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.moku.WhiteBlowRushAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.moku.WhiteLauncherAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.moku.WhiteOutAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.moku.WhitePullAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.moku.WhiteSnakeAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.moku.WhiteStrikeAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.morgan.MorganShockwaveAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.nagi.SilentAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.nekoleopard.ClawStrikeAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.nekoleopard.FerociousLeapAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.nekoleopard.LeopardHeavyPointAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.nekoleopard.LeopardWalkPointAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.nekoleopard.NekoNightVisionAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.netsu.HeatDenasshiAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.netsu.NekkaiGyoraiAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.netsu.NekkaiJigokuAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.netsu.NetsuEnhancementAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.nikyu.HanpatsuAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.nikyu.NikyuPushAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.nikyu.PadHoAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.nikyu.PainRepelAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.nikyu.PuniAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.nikyu.TsuppariPadHoAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.nikyu.UrsusShockAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.noro.KyubiRushAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.noro.NoroNoroBeamAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.noro.NoroNoroBeamSwordAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.ope.CounterShockAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.ope.GammaKnifeAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.ope.InjectionShotAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.ope.MesAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.ope.RoomAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.ope.ShamblesAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.ope.TaktAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.ori.AwaseBaoriAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.ori.BindAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.ori.GreatCageAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.oto.BonAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.oto.DonAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.oto.ShanAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.pero.CandyArmorAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.pero.CandyEscalatorAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.pero.CandyManAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.pero.CandyWallAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.pero.CandyWaveAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.pero.PeroImmunityAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.pika.AmaNoMurakumoAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.pika.AmaterasuAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.pika.FlashAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.pika.LightAccelerationAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.pika.PikaLogiaAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.pika.PikaTravelAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.pika.YasakaniNoMagatamaAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.pika.YataNoKagamiAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.rokushiki.GeppoAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.rokushiki.KamieAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.rokushiki.RankyakuAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.rokushiki.RokuoganAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.rokushiki.ShiganAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.rokushiki.SoruAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.rokushiki.TekkaiAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.ryuallosaurus.AllosaurusHeavyPointAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.ryuallosaurus.AllosaurusRideableAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.ryuallosaurus.AllosaurusWalkPointAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.ryuallosaurus.AncientBiteAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.ryuallosaurus.AncientTailSpinAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.ryubrachiosaurus.BrachioBomberAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.ryubrachiosaurus.BrachioGrabAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.ryubrachiosaurus.BrachiosaurusGuardPointAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.ryubrachiosaurus.BrachiosaurusHeavyPointAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.ryubrachiosaurus.BrachiosaurusRideableAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.ryupteranodon.BarizodonAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.ryupteranodon.BeakGrabAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.ryupteranodon.PteranodonAssaultPointAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.ryupteranodon.PteranodonFlightAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.ryupteranodon.PteranodonFlyPointAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.ryupteranodon.TankyudonAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.ryupteranodon.TempuraudonAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.sabi.RustBreakAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.sabi.RustSkinAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.sabi.RustTouchAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.sai.HornDashAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.sai.RhinoSmashAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.sai.SaiHeavyPointAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.sai.SaiRideableAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.sai.SaiWalkPointAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.saraaxolotl.AxolotlHealAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.saraaxolotl.AxolotlHeavyPointAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.saraaxolotl.AxolotlWalkPointAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.saraaxolotl.HeartRegenAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.saraaxolotl.PlayDeadAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.saraaxolotl.PoisonSpitAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.sniper.HiNoToriBoshiAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.sniper.HissatsuAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.sniper.KaenBoshiAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.sniper.KemuriBoshiAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.sniper.NemuriBoshiAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.sniper.RenpatsuNamariBoshiAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.sniper.SakuretsuSabotenBoshiAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.sniper.TetsuBoshiAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.sniper.TokuyoAburaBoshiAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.sube.SubeSubeDeflectAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.sube.SubeSubeSpurAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.sui.FreeSwimmingAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.sui.NekomimiPunchAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.sui.NyanNyanSuplexAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.sui.NyanNyanSuplexBabyBusterAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.suke.ShishaNoTeAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.suke.SkattingAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.suke.SukePunchAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.suna.BarjanAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.suna.DesertEncierroAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.suna.DesertGirasoleAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.suna.DesertGrandeEspadaAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.suna.DesertSpadaAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.suna.GrandeSablesAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.suna.GroundDeathAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.suna.GroundSeccoAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.suna.SablesAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.suna.SablesGuardAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.suna.SablesPesadoAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.suna.SunaFlyAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.suna.SunaLogiaAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.suna.SunaTravelAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.supa.AtomicRushAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.supa.AtomicSpurtAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.supa.SparClawAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.supa.SparklingDaisyAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.supa.SpiderAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.supa.SpiralHollowAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.swordsman.HiryuKaenAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.swordsman.OTatsumakiAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.swordsman.SanbyakurokujuPoundHoAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.swordsman.ShiShishiSonsonAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.swordsman.YakkodoriAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.toriphoenix.BlueBirdAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.toriphoenix.FlamesOfRegenerationAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.toriphoenix.FujiazamiAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.toriphoenix.PhoenixAssaultPointAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.toriphoenix.PhoenixFlightAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.toriphoenix.PhoenixFlyPointAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.toriphoenix.PhoenixGoenAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.toriphoenix.SaiseiNoHonoAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.toriphoenix.TenseiNoSoenAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.ushibison.BisonHeavyPointAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.ushibison.BisonRideableAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.ushibison.BisonSmashAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.ushibison.BisonWalkPointAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.ushibison.FiddleBanffAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.ushibison.KokuteiCrossAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.ushigiraffe.BiganAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.ushigiraffe.GiraffeHeavyPointAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.ushigiraffe.GiraffeRideableAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.ushigiraffe.GiraffeWalkPointAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.wara.LifeMinusAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.wara.StrawManAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.wara.WarabideSwordAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.yami.AbsorbedBlocksAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.yami.BlackHoleAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.yami.BlackRoadAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.yami.BlackWorldAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.yami.DarkMatterAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.yami.KurouzuAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.yami.LiberationAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.yomi.KasuriutaFubukiGiriAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.yomi.SoulParadeAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.yomi.YomiImmunityAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.yomi.YomiNoReikiAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.yuki.FubukiAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.yuki.KamakuraAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.yuki.KamakuraJussoshiAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.yuki.TabiraYukiAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.yuki.YukiGakiAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.yuki.YukiImmunityAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.yuki.YukiLogiaAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.yuki.YukiRabiAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.yuki.YukiTravelAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.zou.GreatStompAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.zou.IvoryDartAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.zou.IvoryStompAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.zou.TrunkShotAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.zou.ZouGuardPointAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.zou.ZouHeavyPointAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.zou.ZouRideableAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.zoumammoth.AncientStompAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.zoumammoth.AncientSweepAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.zoumammoth.AncientTrunkShotAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.zoumammoth.MammothGuardPointAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.zoumammoth.MammothHeavyPointAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.zoumammoth.MammothRideableAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.zoumammoth.MammothTrampleAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.zushi.AbareHimatsuriAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.zushi.GraviPullAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.zushi.GraviZoneAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.zushi.JigokuTabiAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.zushi.MokoAbility;
/*     */ import xyz.pixelatedw.mineminenomi.abilities.zushi.SagariNoRyuseiAbility;
/*     */ import xyz.pixelatedw.mineminenomi.api.abilities.AbilityCore;
/*     */ import xyz.pixelatedw.mineminenomi.api.enums.FruitType;
/*     */ import xyz.pixelatedw.mineminenomi.items.AkumaNoMiItem;
/*     */ import xyz.pixelatedw.mineminenomi.wypi.WyDebug;
/*     */ import xyz.pixelatedw.mineminenomi.wypi.WyHelper;
/*     */ import xyz.pixelatedw.mineminenomi.wypi.WyRegistry;
/*     */ 
/*     */ 
/*     */ public class ModAbilities
/*     */ {
/* 543 */   public static final AkumaNoMiItem RYU_RYU_NO_MI_ALLOSAURUS = registerFruit(new AkumaNoMiItem("Ryu Ryu no Mi, Model: Allosaurus", 2, FruitType.ANCIENT_ZOAN, new AbilityCore[] { AllosaurusWalkPointAbility.INSTANCE, AllosaurusHeavyPointAbility.INSTANCE, AncientBiteAbility.INSTANCE, AncientTailSpinAbility.INSTANCE, AllosaurusRideableAbility.INSTANCE }));
/* 544 */   public static final AkumaNoMiItem SAI_SAI_NO_MI = registerFruit(new AkumaNoMiItem("Sai Sai no Mi", 2, FruitType.ZOAN, new AbilityCore[] { SaiWalkPointAbility.INSTANCE, SaiHeavyPointAbility.INSTANCE, RhinoSmashAbility.INSTANCE, HornDashAbility.INSTANCE, SaiRideableAbility.INSTANCE }));
/* 545 */   public static final AkumaNoMiItem SARA_SARA_NO_MI_AXOLOTL = registerFruit(new AkumaNoMiItem("Sara Sara no Mi, Model: Axolotl", 2, FruitType.ZOAN, new AbilityCore[] { AxolotlHeavyPointAbility.INSTANCE, AxolotlWalkPointAbility.INSTANCE, PoisonSpitAbility.INSTANCE, AxolotlHealAbility.INSTANCE, PlayDeadAbility.INSTANCE, HeartRegenAbility.INSTANCE }));
/* 546 */   public static final AkumaNoMiItem RYU_RYU_NO_MI_BRACHIOSAURUS = registerFruit(new AkumaNoMiItem("Ryu Ryu no Mi, Model: Brachiosaurus", 2, FruitType.ANCIENT_ZOAN, new AbilityCore[] { BrachiosaurusGuardPointAbility.INSTANCE, BrachiosaurusHeavyPointAbility.INSTANCE, BrachioBomberAbility.INSTANCE, BrachioGrabAbility.INSTANCE, BrachiosaurusRideableAbility.INSTANCE }));
/* 547 */   public static final AkumaNoMiItem RYU_RYU_NO_MI_PTERANODON = registerFruit(new AkumaNoMiItem("Ryu Ryu no Mi, Model: Pteranodon", 2, FruitType.ANCIENT_ZOAN, new AbilityCore[] { PteranodonFlyPointAbility.INSTANCE, PteranodonAssaultPointAbility.INSTANCE, TempuraudonAbility.INSTANCE, TankyudonAbility.INSTANCE, BeakGrabAbility.INSTANCE, BarizodonAbility.INSTANCE, PteranodonFlightAbility.INSTANCE }));
/* 548 */   public static final AkumaNoMiItem KAME_KAME_NO_MI = registerFruit(new AkumaNoMiItem("Kame Kame no Mi", 1, FruitType.ZOAN, new AbilityCore[] { KameGuardPointAbility.INSTANCE, KameWalkPointAbility.INSTANCE, KameRideableAbility.INSTANCE }));
/* 549 */   public static final AkumaNoMiItem NEKO_NEKO_NO_MI_LEOPARD = registerFruit(new AkumaNoMiItem("Neko Neko no Mi, Model: Leopard", 2, FruitType.ZOAN, new AbilityCore[] { LeopardWalkPointAbility.INSTANCE, LeopardHeavyPointAbility.INSTANCE, FerociousLeapAbility.INSTANCE, ClawStrikeAbility.INSTANCE, NekoNightVisionAbility.INSTANCE }));
/* 550 */   public static final AkumaNoMiItem ZOU_ZOU_NO_MI_MAMMOTH = registerFruit(new AkumaNoMiItem("Zou Zou no Mi, Model: Mammoth", 2, FruitType.ANCIENT_ZOAN, new AbilityCore[] { MammothGuardPointAbility.INSTANCE, MammothHeavyPointAbility.INSTANCE, MammothTrampleAbility.INSTANCE, AncientStompAbility.INSTANCE, AncientSweepAbility.INSTANCE, AncientTrunkShotAbility.INSTANCE, MammothRideableAbility.INSTANCE }));
/* 551 */   public static final AkumaNoMiItem HITO_HITO_NO_MI = registerFruit(new AkumaNoMiItem("Hito Hito no Mi", 1, FruitType.ZOAN, new AbilityCore[0]));
/* 552 */   public static final AkumaNoMiItem USHI_USHI_NO_MI_GIRAFFE = registerFruit(new AkumaNoMiItem("Ushi Ushi no Mi, Model: Giraffe", 1, FruitType.ZOAN, new AbilityCore[] { GiraffeHeavyPointAbility.INSTANCE, GiraffeWalkPointAbility.INSTANCE, BiganAbility.INSTANCE, GiraffeRideableAbility.INSTANCE }));
/* 553 */   public static final AkumaNoMiItem MOGU_MOGU_NO_MI = registerFruit(new AkumaNoMiItem("Mogu Mogu no Mi", 1, FruitType.ZOAN, new AbilityCore[] { MoguHeavyPointAbility.INSTANCE, MoguraBananaAbility.INSTANCE, MoguraTonpoAbility.INSTANCE }));
/* 554 */   public static final AkumaNoMiItem USHI_USHI_NO_MI_BISON = registerFruit(new AkumaNoMiItem("Ushi Ushi no Mi, Model: Bison", 2, FruitType.ZOAN, new AbilityCore[] { BisonHeavyPointAbility.INSTANCE, BisonWalkPointAbility.INSTANCE, FiddleBanffAbility.INSTANCE, KokuteiCrossAbility.INSTANCE, BisonSmashAbility.INSTANCE, BisonRideableAbility.INSTANCE }));
/* 555 */   public static final AkumaNoMiItem ZOU_ZOU_NO_MI = registerFruit(new AkumaNoMiItem("Zou Zou no Mi", 2, FruitType.ZOAN, new AbilityCore[] { ZouGuardPointAbility.INSTANCE, ZouHeavyPointAbility.INSTANCE, TrunkShotAbility.INSTANCE, GreatStompAbility.INSTANCE, IvoryDartAbility.INSTANCE, IvoryStompAbility.INSTANCE, ZouRideableAbility.INSTANCE }));
/* 556 */   public static final AkumaNoMiItem HITO_HITO_NO_MI_DAIBUTSU = registerFruit(new AkumaNoMiItem("Hito Hito no Mi, Model: Daibutsu", 3, FruitType.MYTHICAL_ZOAN, new AbilityCore[] { HitoDaibutsuPointAbility.INSTANCE, ImpactBlastAbility.INSTANCE }));
/* 557 */   public static final AkumaNoMiItem TORI_TORI_NO_MI_PHOENIX = registerFruit(new AkumaNoMiItem("Tori Tori no Mi, Model: Phoenix", 3, FruitType.MYTHICAL_ZOAN, new AbilityCore[] { PhoenixAssaultPointAbility.INSTANCE, PhoenixFlyPointAbility.INSTANCE, PhoenixGoenAbility.INSTANCE, SaiseiNoHonoAbility.INSTANCE, FujiazamiAbility.INSTANCE, TenseiNoSoenAbility.INSTANCE, BlueBirdAbility.INSTANCE, FlamesOfRegenerationAbility.INSTANCE, PhoenixFlightAbility.INSTANCE }));
/*     */ 
/*     */   
/* 560 */   public static final AkumaNoMiItem MANE_MANE_NO_MI = registerFruit(new AkumaNoMiItem("Mane Mane no Mi", 2, FruitType.PARAMECIA, new AbilityCore[] { ManeManeMemoryAbility.INSTANCE }));
/* 561 */   public static final AkumaNoMiItem DEKA_DEKA_NO_MI = registerFruit(new AkumaNoMiItem("Deka Deka no Mi", 1, FruitType.PARAMECIA, new AbilityCore[] { DekaDekaAbility.INSTANCE, DekaTrampleAbility.INSTANCE }));
/* 562 */   public static final AkumaNoMiItem KARU_KARU_NO_MI = registerFruit(new AkumaNoMiItem("Karu Karu no Mi", 2, FruitType.PARAMECIA, new AbilityCore[] { IngaZarashiAbility.INSTANCE, KarmaAbility.INSTANCE }));
/* 563 */   public static final AkumaNoMiItem JIKI_JIKI_NO_MI = registerFruit(new AkumaNoMiItem("Jiki Jiki no Mi", 3, FruitType.PARAMECIA, new AbilityCore[] { AttractAbility.INSTANCE, RepelAbility.INSTANCE, PunkGibsonAbility.INSTANCE, PunkPistolsAbility.INSTANCE, PunkCornaDioAbility.INSTANCE, DamnedPunkAbility.INSTANCE, MagneticItemsAbility.INSTANCE, GenocideRaidAbility.INSTANCE, PunkCrossAbility.INSTANCE }));
/*     */   
/* 565 */   public static final AkumaNoMiItem OTO_OTO_NO_MI = registerFruit(new AkumaNoMiItem("Oto Oto no Mi", 2, FruitType.PARAMECIA, new AbilityCore[] { BonAbility.INSTANCE, DonAbility.INSTANCE, ShanAbility.INSTANCE }));
/* 566 */   public static final AkumaNoMiItem BARA_BARA_NO_MI = registerFruit(new AkumaNoMiItem("Bara Bara No Mi", 2, FruitType.PARAMECIA, new AbilityCore[] { BaraBaraHoAbility.INSTANCE, BaraBaraFestivalAbility.INSTANCE, KuchuKirimomiDaiCircusAbility.INSTANCE, BaraBaraCarAbility.INSTANCE, BaraSplitAbility.INSTANCE, SlashDamageImmunityAbility.BARA_INSTANCE }));
/* 567 */   public static final AkumaNoMiItem SUBE_SUBE_NO_MI = registerFruit(new AkumaNoMiItem("Sube Sube No Mi", 1, FruitType.PARAMECIA, new AbilityCore[] { SubeSubeSpurAbility.INSTANCE, SubeSubeDeflectAbility.INSTANCE, HandcuffsImmunityAbility.INSTANCE }));
/* 568 */   public static final AkumaNoMiItem KOBU_KOBU_NO_MI = registerFruit(new AkumaNoMiItem("Kobu Kobu No Mi", 1, FruitType.PARAMECIA, new AbilityCore[] { ShoureiAbility.INSTANCE, NegativeImmunityAbility.INSTANCE }));
/* 569 */   public static final AkumaNoMiItem HANA_HANA_NO_MI = registerFruit(new AkumaNoMiItem("Hana Hana No Mi", 2, FruitType.PARAMECIA, new AbilityCore[] { DosFleurClutchAbility.INSTANCE, SeisFleurSlapAbility.INSTANCE, SeisFleurTwistAbility.INSTANCE, VeinteFleurCalendulaAbility.INSTANCE, CienFleurWingAbility.INSTANCE, CienFleurStompAbility.INSTANCE, CampoDeFloresAbility.INSTANCE, MilFleurAbility.INSTANCE }));
/* 570 */   public static final AkumaNoMiItem MINI_MINI_NO_MI = registerFruit(new AkumaNoMiItem("Mini Mini No Mi", 1, FruitType.PARAMECIA, new AbilityCore[] { MiniMiniAbility.INSTANCE, PaperFloatAbility.INSTANCE }));
/* 571 */   public static final AkumaNoMiItem HISO_HISO_NO_MI = registerFruit(new AkumaNoMiItem("Hiso Hiso No Mi", 1, FruitType.PARAMECIA, new AbilityCore[] { ForewarnAbility.INSTANCE, LookoutAbility.INSTANCE, AnimalFriendAbility.INSTANCE }));
/* 572 */   public static final AkumaNoMiItem KUKU_KUKU_NO_MI = registerFruit(new AkumaNoMiItem("Kuku Kuku no Mi", 1, FruitType.PARAMECIA, new AbilityCore[] { GourmetamorphosisAbility.INSTANCE, GastronomorphAbility.INSTANCE, GourmetSnipeAbility.INSTANCE }));
/* 573 */   public static final AkumaNoMiItem KIRA_KIRA_NO_MI = registerFruit(new AkumaNoMiItem("Kira Kira no Mi", 2, FruitType.PARAMECIA, new AbilityCore[] { DiamondBodyAbility.INSTANCE, BrilliantPunkAbility.INSTANCE, CabochonKnuckleAbility.INSTANCE }));
/*     */   
/* 575 */   public static final AkumaNoMiItem BETA_BETA_NO_MI = registerFruit(new AkumaNoMiItem("Beta Beta no Mi", 2, FruitType.PARAMECIA, new AbilityCore[] { BetaCoatingAbility.INSTANCE, BetaLauncherAbility.INSTANCE, HanamizuShinkenAbility.INSTANCE, BetaBetaChainAbility.INSTANCE, BetaImmunityAbility.INSTANCE }));
/* 576 */   public static final AkumaNoMiItem NAGI_NAGI_NO_MI = registerFruit(new AkumaNoMiItem("Nagi Nagi no Mi", 1, FruitType.PARAMECIA, new AbilityCore[] { SilentAbility.INSTANCE }));
/* 577 */   public static final AkumaNoMiItem PERO_PERO_NO_MI = registerFruit(new AkumaNoMiItem("Pero Pero no Mi", 2, FruitType.PARAMECIA, new AbilityCore[] { CandyManAbility.INSTANCE, CandyWallAbility.INSTANCE, CandyEscalatorAbility.INSTANCE, CandyWaveAbility.INSTANCE, CandyArmorAbility.INSTANCE, PeroImmunityAbility.INSTANCE }));
/* 578 */   public static final AkumaNoMiItem NETSU_NETSU_NO_MI = registerFruit(new AkumaNoMiItem("Netsu Netsu no Mi", 2, FruitType.PARAMECIA, new AbilityCore[] { NetsuEnhancementAbility.INSTANCE, NekkaiJigokuAbility.INSTANCE, NekkaiGyoraiAbility.INSTANCE, HeatDenasshiAbility.INSTANCE, HeatImmunityAbility.INSTANCE }));
/* 579 */   public static final AkumaNoMiItem SUI_SUI_NO_MI = registerFruit(new AkumaNoMiItem("Sui Sui no Mi", 2, FruitType.PARAMECIA, new AbilityCore[] { FreeSwimmingAbility.INSTANCE, NekomimiPunchAbility.INSTANCE, NyanNyanSuplexAbility.INSTANCE, NyanNyanSuplexBabyBusterAbility.INSTANCE }));
/*     */   
/* 581 */   public static final AkumaNoMiItem AWA_AWA_NO_MI = registerFruit(new AkumaNoMiItem("Awa Awa no Mi", 1, FruitType.PARAMECIA, new AbilityCore[] { GoldenHourAbility.INSTANCE, RelaxHourAbility.INSTANCE, SoapDefenseAbility.INSTANCE }));
/*     */   
/* 583 */   public static final AkumaNoMiItem WARA_WARA_NO_MI = registerFruit(new AkumaNoMiItem("Wara Wara no Mi", 3, FruitType.PARAMECIA, new AbilityCore[] { StrawManAbility.INSTANCE, WarabideSwordAbility.INSTANCE, LifeMinusAbility.INSTANCE }));
/* 584 */   public static final AkumaNoMiItem KACHI_KACHI_NO_MI = registerFruit(new AkumaNoMiItem("Kachi Kachi no Mi", 1, FruitType.PARAMECIA, new AbilityCore[] { EvaporateAbility.INSTANCE, HotBoilingSpecialAbility.INSTANCE, VulcanizationAbility.INSTANCE }));
/* 585 */   public static final AkumaNoMiItem DOA_DOA_NO_MI = registerFruit(new AkumaNoMiItem("Doa Doa no Mi", 2, FruitType.PARAMECIA, new AbilityCore[] { DoorDoorAbility.INSTANCE, KaitenDoorAbility.INSTANCE, AirDoorAbility.INSTANCE }));
/* 586 */   public static final AkumaNoMiItem CHIYU_CHIYU_NO_MI = registerFruit(new AkumaNoMiItem("Chiyu Chiyu no Mi", 1, FruitType.PARAMECIA, new AbilityCore[] { HealingTouchAbility.INSTANCE, ChiyupopoAbility.INSTANCE, KenpopoAbility.INSTANCE, TearsAbility.INSTANCE }));
/* 587 */   public static final AkumaNoMiItem SABI_SABI_NO_MI = registerFruit(new AkumaNoMiItem("Sabi Sabi no Mi", 1, FruitType.PARAMECIA, new AbilityCore[] { RustTouchAbility.INSTANCE, RustBreakAbility.INSTANCE, RustSkinAbility.INSTANCE }));
/* 588 */   public static final AkumaNoMiItem YOMI_YOMI_NO_MI = registerFruit(new AkumaNoMiItem("Yomi Yomi no Mi", 2, FruitType.PARAMECIA, new AbilityCore[] { SoulParadeAbility.INSTANCE, KasuriutaFubukiGiriAbility.INSTANCE, YomiNoReikiAbility.INSTANCE, YomiImmunityAbility.INSTANCE }));
/* 589 */   public static final AkumaNoMiItem BAKU_BAKU_NO_MI = registerFruit(new AkumaNoMiItem("Baku Baku no Mi", 1, FruitType.PARAMECIA, new AbilityCore[] { BakuMunchAbility.INSTANCE, BeroCannonAbility.INSTANCE, BakuTsuihoAbility.INSTANCE, BakuFactoryAbility.INSTANCE }));
/* 590 */   public static final AkumaNoMiItem HORU_HORU_NO_MI = registerFruit(new AkumaNoMiItem("Horu Horu no Mi", 1, FruitType.PARAMECIA, new AbilityCore[] { OnnaHormoneAbility.INSTANCE, ChiyuHormoneAbility.INSTANCE, TensionHormoneAbility.INSTANCE, GanmenSeichoHormoneAbility.INSTANCE, DeathWinkAbility.INSTANCE }));
/* 591 */   public static final AkumaNoMiItem KILO_KILO_NO_MI = registerFruit(new AkumaNoMiItem("Kilo Kilo no Mi", 1, FruitType.PARAMECIA, new AbilityCore[] { KiloPress1Ability.INSTANCE, KiloPress10000Ability.INSTANCE, KiloPunch5000Ability.INSTANCE }));
/* 592 */   public static final AkumaNoMiItem GOE_GOE_NO_MI = registerFruit(new AkumaNoMiItem("Goe Goe no Mi", 1, FruitType.PARAMECIA, new AbilityCore[] { TodorokiAbility.INSTANCE, DragonsRoarAbility.INSTANCE }));
/* 593 */   public static final AkumaNoMiItem MERO_MERO_NO_MI = registerFruit(new AkumaNoMiItem("Mero Mero no Mi", 2, FruitType.PARAMECIA, new AbilityCore[] { MeroMeroMellowAbility.INSTANCE, PistolKissAbility.INSTANCE, SlaveArrowAbility.INSTANCE, PerfumeFemurAbility.INSTANCE }));
/* 594 */   public static final AkumaNoMiItem ORI_ORI_NO_MI = registerFruit(new AkumaNoMiItem("Ori Ori no Mi", 1, FruitType.PARAMECIA, new AbilityCore[] { BindAbility.INSTANCE, GreatCageAbility.INSTANCE, AwaseBaoriAbility.INSTANCE }));
/* 595 */   public static final AkumaNoMiItem SUPA_SUPA_NO_MI = registerFruit(new AkumaNoMiItem("Supa Supa no Mi", 2, FruitType.PARAMECIA, new AbilityCore[] { SpiderAbility.INSTANCE, SparClawAbility.INSTANCE, SpiralHollowAbility.INSTANCE, SparklingDaisyAbility.INSTANCE, AtomicSpurtAbility.INSTANCE }));
/* 596 */   public static final AkumaNoMiItem HORO_HORO_NO_MI = registerFruit(new AkumaNoMiItem("Horo Horo no Mi", 2, FruitType.PARAMECIA, new AbilityCore[] { NegativeHollowAbility.INSTANCE, MiniHollowAbility.INSTANCE, TokuHollowAbility.INSTANCE, YutaiRidatsuAbility.INSTANCE }));
/* 597 */   public static final AkumaNoMiItem ITO_ITO_NO_MI = registerFruit(new AkumaNoMiItem("Ito Ito no Mi", 3, FruitType.PARAMECIA, new AbilityCore[] { ParasiteAbility.INSTANCE, SoraNoMichiAbility.INSTANCE, TamaitoAbility.INSTANCE, FullbrightAbility.INSTANCE, OverheatAbility.INSTANCE, KumoNoSugakiAbility.INSTANCE, TorikagoAbility.INSTANCE, BlackKnightAbility.INSTANCE }));
/* 598 */   public static final AkumaNoMiItem ZUSHI_ZUSHI_NO_MI = registerFruit(new AkumaNoMiItem("Zushi Zushi no Mi", 3, FruitType.PARAMECIA, new AbilityCore[] { JigokuTabiAbility.INSTANCE, SagariNoRyuseiAbility.INSTANCE, MokoAbility.INSTANCE, AbareHimatsuriAbility.INSTANCE, GraviZoneAbility.INSTANCE, GraviPullAbility.INSTANCE }));
/* 599 */   public static final AkumaNoMiItem BARI_BARI_NO_MI = registerFruit(new AkumaNoMiItem("Bari Bari no Mi", 1, FruitType.PARAMECIA, new AbilityCore[] { BarrierAbility.INSTANCE, BarrierBallAbility.INSTANCE, BarrierCrashAbility.INSTANCE, BariBariNoPistolAbility.INSTANCE, BarrierbilityStairsAbility.INSTANCE, BarrierbilityBatAbility.INSTANCE }));
/* 600 */   public static final AkumaNoMiItem DOKU_DOKU_NO_MI = registerFruit(new AkumaNoMiItem("Doku Doku no Mi", 3, FruitType.PARAMECIA, new AbilityCore[] { HydraAbility.INSTANCE, ChloroBallAbility.INSTANCE, DokuFuguAbility.INSTANCE, VenomRoadAbility.INSTANCE, DokuGumoAbility.INSTANCE, VenomDemonAbility.INSTANCE, PoisonImmunityAbility.INSTANCE }));
/* 601 */   public static final AkumaNoMiItem DORU_DORU_NO_MI = registerFruit(new AkumaNoMiItem("Doru Doru no Mi", 2, FruitType.PARAMECIA, new AbilityCore[] { CandleWallAbility.INSTANCE, CandleHouseAbility.INSTANCE, DoruDoruArtsMoriAbility.INSTANCE, DoruDoruArtsKenAbility.INSTANCE, CandleLockAbility.INSTANCE, DoruDoruArtsPickaxeAbility.INSTANCE, DoruDoruBallAbility.INSTANCE, DoruDoruNoYakataAbility.INSTANCE, CandleChampionAbility.INSTANCE }));
/* 602 */   public static final AkumaNoMiItem KAGE_KAGE_NO_MI = registerFruit(new AkumaNoMiItem("Kage Kage no Mi", 2, FruitType.PARAMECIA, new AbilityCore[] { DoppelmanAbility.INSTANCE, KagemushaAbility.INSTANCE, BrickBatAbility.INSTANCE, BlackBoxAbility.INSTANCE, TsunoTokageAbility.INSTANCE, KageKakumeiAbility.INSTANCE, KageGiriAbility.INSTANCE, NightmareSoldiersAbility.INSTANCE, ShadowsAsgardAbility.INSTANCE }));
/* 603 */   public static final AkumaNoMiItem GURA_GURA_NO_MI = registerFruit(new AkumaNoMiItem("Gura Gura no Mi", 3, FruitType.PARAMECIA, new AbilityCore[] { GekishinAbility.INSTANCE, ShingenNoIchigekiAbility.INSTANCE, TenchiMeidoAbility.INSTANCE, ShimaYurashiAbility.INSTANCE, GuraImmunityAbility.INSTANCE, KabutowariAbility.INSTANCE }));
/* 604 */   public static final AkumaNoMiItem BOMU_BOMU_NO_MI = registerFruit(new AkumaNoMiItem("Bomu Bomu no Mi", 2, FruitType.PARAMECIA, new AbilityCore[] { NoseFancyCannonAbility.INSTANCE, KickBombAbility.INSTANCE, ZenshinKibakuAbility.INSTANCE, ExplosivePunchAbility.INSTANCE, BreezeBreathBombAbility.INSTANCE, ExplosionImmunityAbility.INSTANCE }));
/* 605 */   public static final AkumaNoMiItem NIKYU_NIKYU_NO_MI = registerFruit(new AkumaNoMiItem("Nikyu Nikyu no Mi", 3, FruitType.PARAMECIA, new AbilityCore[] { PadHoAbility.INSTANCE, HanpatsuAbility.INSTANCE, TsuppariPadHoAbility.INSTANCE, UrsusShockAbility.INSTANCE, PuniAbility.INSTANCE, NikyuPushAbility.INSTANCE, PainRepelAbility.INSTANCE }));
/* 606 */   public static final AkumaNoMiItem NORO_NORO_NO_MI = registerFruit(new AkumaNoMiItem("Noro Noro no Mi", 1, FruitType.PARAMECIA, new AbilityCore[] { NoroNoroBeamAbility.INSTANCE, NoroNoroBeamSwordAbility.INSTANCE, KyubiRushAbility.INSTANCE }));
/* 607 */   public static final AkumaNoMiItem OPE_OPE_NO_MI = registerFruit(new AkumaNoMiItem("Ope Ope no Mi", 2, FruitType.PARAMECIA, new AbilityCore[] { RoomAbility.INSTANCE, ShamblesAbility.INSTANCE, TaktAbility.INSTANCE, InjectionShotAbility.INSTANCE, CounterShockAbility.INSTANCE, MesAbility.INSTANCE, GammaKnifeAbility.INSTANCE }));
/* 608 */   public static final AkumaNoMiItem SUKE_SUKE_NO_MI = registerFruit(new AkumaNoMiItem("Suke Suke no Mi", 1, FruitType.PARAMECIA, new AbilityCore[] { SkattingAbility.INSTANCE, ShishaNoTeAbility.INSTANCE, SukePunchAbility.INSTANCE }));
/* 609 */   public static final AkumaNoMiItem GOMU_GOMU_NO_MI = registerFruit(new AkumaNoMiItem("Gomu Gomu no Mi", 2, FruitType.PARAMECIA, new AbilityCore[] { GomuGomuNoPistolAbility.INSTANCE, GomuGomuNoGatlingAbility.INSTANCE, GomuGomuNoBazookaAbility.INSTANCE, GomuGomuNoRocketAbility.INSTANCE, GearSecondAbility.INSTANCE, GearThirdAbility.INSTANCE, GearFourthAbility.INSTANCE, GearFourthFlightAbility.INSTANCE, BouncyAbility.INSTANCE, GearFifthAbility.INSTANCE, GomuGomuNoGigantAbility.INSTANCE, GomuGomuNoDawnWhipAbility.INSTANCE }));
/* 610 */   public static final AkumaNoMiItem BANE_BANE_NO_MI = registerFruit(new AkumaNoMiItem("Bane Bane no Mi", 1, FruitType.PARAMECIA, new AbilityCore[] { SpringHopperAbility.INSTANCE, SpringSnipeAbility.INSTANCE, SpringDeathKnockAbility.INSTANCE, NoFallDamageAbility.INSTANCE }));
/*     */ 
/*     */   
/* 613 */   public static final AkumaNoMiItem YUKI_YUKI_NO_MI = registerFruit(new AkumaNoMiItem("Yuki Yuki no Mi", 3, FruitType.LOGIA, new AbilityCore[] { KamakuraAbility.INSTANCE, YukiRabiAbility.INSTANCE, KamakuraJussoshiAbility.INSTANCE, TabiraYukiAbility.INSTANCE, YukiGakiAbility.INSTANCE, FubukiAbility.INSTANCE, YukiLogiaAbility.INSTANCE, YukiImmunityAbility.INSTANCE, YukiTravelAbility.INSTANCE }));
/* 614 */   public static final AkumaNoMiItem YAMI_YAMI_NO_MI = registerFruit(new AkumaNoMiItem("Yami Yami no Mi", 3, FruitType.LOGIA, new AbilityCore[] { BlackHoleAbility.INSTANCE, BlackRoadAbility.INSTANCE, LiberationAbility.INSTANCE, KurouzuAbility.INSTANCE, DarkMatterAbility.INSTANCE, BlackWorldAbility.INSTANCE, AbsorbedBlocksAbility.INSTANCE }));
/* 615 */   public static final AkumaNoMiItem GASU_GASU_NO_MI = registerFruit(new AkumaNoMiItem("Gasu Gasu no Mi", 3, FruitType.LOGIA, new AbilityCore[] { GasRobeAbility.INSTANCE, GastanetAbility.INSTANCE, GastilleAbility.INSTANCE, BlueSwordAbility.INSTANCE, KarakuniAbility.INSTANCE, ShinokuniAbility.INSTANCE, KoroAbility.INSTANCE, GasuFlyAbility.INSTANCE, GasuImmunityAbility.INSTANCE, GasuLogiaAbility.INSTANCE }));
/* 616 */   public static final AkumaNoMiItem MAGU_MAGU_NO_MI = registerFruit(new AkumaNoMiItem("Magu Magu no Mi", 3, FruitType.LOGIA, new AbilityCore[] { DaiFunkaAbility.INSTANCE, RyuseiKazanAbility.INSTANCE, MeigoAbility.INSTANCE, BakuretsuKazanAbility.INSTANCE, LavaFlowAbility.INSTANCE, MagmaCoatingAbility.INSTANCE, MaguLogiaAbility.INSTANCE, LogiaHeatImmunityAbility.INSTANCE }));
/* 617 */   public static final AkumaNoMiItem SUNA_SUNA_NO_MI = registerFruit(new AkumaNoMiItem("Suna Suna no Mi", 3, FruitType.LOGIA, new AbilityCore[] { DesertSpadaAbility.INSTANCE, DesertGrandeEspadaAbility.INSTANCE, SablesAbility.INSTANCE, GrandeSablesAbility.INSTANCE, BarjanAbility.INSTANCE, DesertEncierroAbility.INSTANCE, GroundDeathAbility.INSTANCE, DesertGirasoleAbility.INSTANCE, SunaFlyAbility.INSTANCE, SablesPesadoAbility.INSTANCE, SunaLogiaAbility.INSTANCE, LogiaImmunityAbility.INSTANCE, SunaTravelAbility.INSTANCE }));
/* 618 */   public static final AkumaNoMiItem GORO_GORO_NO_MI = registerFruit(new AkumaNoMiItem("Goro Goro no Mi", 3, FruitType.LOGIA, new AbilityCore[] { SparkStepAbility.INSTANCE, ElThorAbility.INSTANCE, VariAbility.INSTANCE, KariAbility.INSTANCE, SangoAbility.INSTANCE, VoltAmaruAbility.INSTANCE, VoltAmaruFlightAbility.INSTANCE, RaigoAbility.INSTANCE, GoroLogiaAbility.INSTANCE, LogiaHeatImmunityAbility.INSTANCE, GoroTravelAbility.INSTANCE }));
/* 619 */   public static final AkumaNoMiItem MOKU_MOKU_NO_MI = registerFruit(new AkumaNoMiItem("Moku Moku no Mi", 3, FruitType.LOGIA, new AbilityCore[] { WhiteBlowAbility.INSTANCE, WhiteSnakeAbility.INSTANCE, WhiteLauncherAbility.INSTANCE, WhiteStrikeAbility.INSTANCE, WhiteBlowRushAbility.INSTANCE, WhiteOutAbility.INSTANCE, MokuFlyAbility.INSTANCE, WhitePullAbility.INSTANCE, SmokeLaunchAbility.INSTANCE, MokuLogiaAbility.INSTANCE, MokuImmunityAbility.INSTANCE }));
/* 620 */   public static final AkumaNoMiItem PIKA_PIKA_NO_MI = registerFruit(new AkumaNoMiItem("Pika Pika no Mi", 3, FruitType.LOGIA, new AbilityCore[] { YataNoKagamiAbility.INSTANCE, YasakaniNoMagatamaAbility.INSTANCE, AmaNoMurakumoAbility.INSTANCE, AmaterasuAbility.INSTANCE, FlashAbility.INSTANCE, PikaLogiaAbility.INSTANCE, LightAccelerationAbility.INSTANCE, LogiaImmunityAbility.INSTANCE, PikaTravelAbility.INSTANCE }));
/* 621 */   public static final AkumaNoMiItem HIE_HIE_NO_MI = registerFruit(new AkumaNoMiItem("Hie Hie no Mi", 3, FruitType.LOGIA, new AbilityCore[] { IceBlockPartisanAbility.INSTANCE, IceAgeAbility.INSTANCE, IceBallAbility.INSTANCE, IceSaberAbility.INSTANCE, IceTimeAbility.INSTANCE, IceBlockPheasantAbility.INSTANCE, IceBlockAvalancheAbility.INSTANCE, HieLogiaAbility.INSTANCE, FrostWalkerAbility.INSTANCE, HieImmunityAbility.INSTANCE, HieTravelAbility.INSTANCE }));
/* 622 */   public static final AkumaNoMiItem MERA_MERA_NO_MI = registerFruit(new AkumaNoMiItem("Mera Mera no Mi", 3, FruitType.LOGIA, new AbilityCore[] { HikenAbility.INSTANCE, HiganAbility.INSTANCE, DaiEnkaiAbility.INSTANCE, HidarumaAbility.INSTANCE, JujikaAbility.INSTANCE, HeatDashAbility.INSTANCE, KyokaenAbility.INSTANCE, HibashiraAbility.INSTANCE, MeraLogiaAbility.INSTANCE, LogiaHeatImmunityAbility.INSTANCE }));
/*     */   
/* 624 */   public static final AbilityCore[] HAKI_ABILITIES = new AbilityCore[] { BusoshokuHakiHardeningAbility.INSTANCE, BusoshokuHakiFullBodyHardeningAbility.INSTANCE, BusoshokuHakiEmissionAbility.INSTANCE, BusoshokuHakiInternalDestructionAbility.INSTANCE, BusoshokuHakiImbuingAbility.INSTANCE, KenbunshokuHakiAuraAbility.INSTANCE, KenbunshokuHakiFutureSightAbility.INSTANCE, HaoshokuHakiAbility.INSTANCE, HaoshokuHakiInfusionAbility.INSTANCE };
/*     */   
/* 626 */   public static final AbilityCore[] MARINE_ABILITIES = new AbilityCore[] { SmallMusterAbility.INSTANCE, MusterAbility.INSTANCE };
/*     */   
/* 628 */   public static final AbilityCore[] HUMAN_ABILITIES = new AbilityCore[] { SoruAbility.INSTANCE, TekkaiAbility.INSTANCE, ShiganAbility.INSTANCE, RankyakuAbility.INSTANCE, KamieAbility.INSTANCE, GeppoAbility.INSTANCE, RokuoganAbility.INSTANCE };
/* 629 */   public static final AbilityCore[] FISHMAN_ABILITIES = new AbilityCore[] { UchimizuAbility.INSTANCE, SamehadaShoteiAbility.INSTANCE, MurasameAbility.INSTANCE, KarakusagawaraSeikenAbility.INSTANCE, KachiageHaisokuAbility.INSTANCE, TwoFishEngineAbility.INSTANCE, YarinamiAbility.INSTANCE, FishmanPassiveBonusesAbility.INSTANCE };
/* 630 */   public static final AbilityCore[] CYBORG_ABILITIES = new AbilityCore[] { StrongRightAbility.INSTANCE, RadicalBeamAbility.INSTANCE, FreshFireAbility.INSTANCE, CoupDeBooAbility.INSTANCE, CoupDeVentAbility.INSTANCE, ColaOverdriveAbility.INSTANCE, SouthlandSuplexAbility.INSTANCE, ColaFuelAbility.INSTANCE, CyborgPassiveBonusesAbility.INSTANCE };
/* 631 */   public static final AbilityCore[] MINK_ABILITIES = new AbilityCore[] { EleclawAbility.INSTANCE, ElectricalMissileAbility.INSTANCE, ElectricalTempestaAbility.INSTANCE, ElectricalShowerAbility.INSTANCE, ElectricalLunaAbility.INSTANCE, SulongAbility.INSTANCE, SulongCheckAbility.INSTANCE, MinkPassiveBonusesAbility.INSTANCE };
/*     */   
/* 633 */   public static final AbilityCore[] SWORDSMAN_ABILITIES = new AbilityCore[] { ShiShishiSonsonAbility.INSTANCE, YakkodoriAbility.INSTANCE, SanbyakurokujuPoundHoAbility.INSTANCE, OTatsumakiAbility.INSTANCE, HiryuKaenAbility.INSTANCE };
/* 634 */   public static final AbilityCore[] SNIPER_ABILITIES = new AbilityCore[] { HiNoToriBoshiAbility.INSTANCE, KemuriBoshiAbility.INSTANCE, RenpatsuNamariBoshiAbility.INSTANCE, SakuretsuSabotenBoshiAbility.INSTANCE, TetsuBoshiAbility.INSTANCE, TokuyoAburaBoshiAbility.INSTANCE, NemuriBoshiAbility.INSTANCE, HissatsuAbility.INSTANCE };
/* 635 */   public static final AbilityCore[] DOCTOR_ABILITIES = new AbilityCore[] { FirstAidAbility.INSTANCE, MedicBagExplosionAbility.INSTANCE, FailedExperimentAbility.INSTANCE, DopingAbility.INSTANCE, AntidoteShotAbility.INSTANCE, VirusZoneAbility.INSTANCE };
/* 636 */   public static final AbilityCore[] ART_OF_WEATHER_ABILITIES = new AbilityCore[] { HeatBallAbility.INSTANCE, CoolBallAbility.INSTANCE, WeatherCloudTempo.INSTANCE, ThunderBallAbility.INSTANCE, ThunderboltTempo.INSTANCE, ThunderstormTempo.INSTANCE, ThunderLanceTempo.INSTANCE, FogTempo.INSTANCE, MirageTempo.INSTANCE, RainTempo.INSTANCE, WeatherEggAbility.INSTANCE, GustSwordAbility.INSTANCE, HeatEggTempo.INSTANCE, CycloneTempo.INSTANCE };
/* 637 */   public static final AbilityCore[] BLACK_LEG_ABILITIES = new AbilityCore[] { DiableJambeAbility.INSTANCE, SkywalkAbility.INSTANCE, AntiMannerKickCourseAbility.INSTANCE, ExtraHachisAbility.INSTANCE, PartyTableKickCourseAbility.INSTANCE, ConcasseAbility.INSTANCE, BienCuitGrillShotAbility.INSTANCE, BlackLegPassiveBonusesAbility.INSTANCE };
/* 638 */   public static final AbilityCore[] BRAWLER_ABILITIES = new AbilityCore[] { GenkotsuMeteorAbility.INSTANCE, KingPunchAbility.INSTANCE, HakaiHoAbility.INSTANCE, JishinHoAbility.INSTANCE, SpinningBrawlAbility.INSTANCE, SuplexAbility.INSTANCE, RyuNoKagizumeAbility.INSTANCE, RyuNoIbukiAbility.INSTANCE, BrawlerPassiveBonusesAbility.INSTANCE };
/*     */   
/* 640 */   public static final AbilityCore[] EXTENDED_FISHMAN_ABILITIES = new AbilityCore[] { SharkOnToothAbility.INSTANCE, MizuTaihoAbility.INSTANCE, MizuOsuAbility.INSTANCE, MizuShuryudanAbility.INSTANCE };
/* 641 */   public static final AbilityCore[] MAN_DEMON_TACTICS_ABILITIES = new AbilityCore[] { DemonicDanceAbility.INSTANCE, DemonicSmashAbility.INSTANCE, DemonicDashAbility.INSTANCE };
/* 642 */   public static final AbilityCore[] CARNIVAL_TRICKS_ABILITIES = new AbilityCore[] { IchirinZashiAbility.INSTANCE, KamikazeHyakkomaGekijoAbility.INSTANCE, KajiOyajiAbility.INSTANCE };
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   private static <T extends AkumaNoMiItem> T registerFruit(T fruit) {
/* 652 */     String resourceName = WyHelper.getResourceName(fruit.getDevilFruitName());
/* 653 */     WyRegistry.getLangMap().put("item.mineminenomi." + resourceName, fruit.getDevilFruitName());
/*     */     
/* 655 */     WyRegistry.registerItem(fruit.getDevilFruitName(), () -> fruit);
/* 656 */     if (fruit.getAbilities() != null && (fruit.getAbilities()).length > 0) {
/* 657 */       registerAbilities(fruit.getAbilities());
/*     */     }
/*     */     
/* 660 */     return fruit;
/*     */   }
/*     */   
/*     */   private static void registerAbilities(AbilityCore[] abilities) {
/* 664 */     Arrays.<AbilityCore>stream(abilities).filter(Objects::nonNull).forEach(abl -> WyRegistry.registerAbility(abl));
/*     */   }
/*     */   
/*     */   public static void register(IEventBus eventBus) {
/* 668 */     WyRegistry.ABILITIES.register(eventBus);
/*     */     
/* 670 */     registerAbilities(HUMAN_ABILITIES);
/* 671 */     registerAbilities(FISHMAN_ABILITIES);
/* 672 */     registerAbilities(CYBORG_ABILITIES);
/* 673 */     registerAbilities(MINK_ABILITIES);
/*     */     
/* 675 */     registerAbilities(SWORDSMAN_ABILITIES);
/* 676 */     registerAbilities(SNIPER_ABILITIES);
/* 677 */     registerAbilities(DOCTOR_ABILITIES);
/* 678 */     registerAbilities(ART_OF_WEATHER_ABILITIES);
/* 679 */     registerAbilities(BLACK_LEG_ABILITIES);
/* 680 */     registerAbilities(BRAWLER_ABILITIES);
/*     */     
/* 682 */     registerAbilities(EXTENDED_FISHMAN_ABILITIES);
/* 683 */     registerAbilities(MAN_DEMON_TACTICS_ABILITIES);
/* 684 */     registerAbilities(CARNIVAL_TRICKS_ABILITIES);
/*     */     
/* 686 */     registerAbilities(HAKI_ABILITIES);
/*     */     
/* 688 */     registerAbilities(MARINE_ABILITIES);
/*     */     
/* 690 */     WyRegistry.registerAbility(CommandAbility.INSTANCE);
/* 691 */     WyRegistry.registerAbility(KnockdownAbility.INSTANCE);
/* 692 */     WyRegistry.registerAbility(EmptyHandsAbility.INSTANCE);
/*     */ 
/*     */     
/* 695 */     WyRegistry.registerAbility(ZoomAbility.INSTANCE);
/*     */ 
/*     */     
/* 698 */     WyRegistry.registerAbility(GunArrayAbility.INSTANCE);
/*     */ 
/*     */     
/* 701 */     WyRegistry.registerAbility(ColaBackpackBonusAbility.INSTANCE);
/*     */ 
/*     */ 
/*     */ 
/*     */     
/* 706 */     WyRegistry.registerAbility(PunchRushAbility.INSTANCE);
/* 707 */     WyRegistry.registerAbility(ChargedPunchAbility.INSTANCE);
/* 708 */     WyRegistry.registerAbility(ChargedCleaveAbility.INSTANCE);
/* 709 */     WyRegistry.registerAbility(AtomicRushAbility.INSTANCE);
/* 710 */     WyRegistry.registerAbility(MorganShockwaveAbility.INSTANCE);
/* 711 */     WyRegistry.registerAbility(TokudaiCandleAbility.INSTANCE);
/* 712 */     WyRegistry.registerAbility(KaenBoshiAbility.INSTANCE);
/* 713 */     WyRegistry.registerAbility(DamageAbsorptionAbility.INSTANCE);
/* 714 */     WyRegistry.registerAbility(TackleAbility.INSTANCE);
/* 715 */     WyRegistry.registerAbility(BellyFlopAbility.INSTANCE);
/* 716 */     WyRegistry.registerAbility(SlamAbility.INSTANCE);
/* 717 */     WyRegistry.registerAbility(WeaponThrowAbility.INSTANCE);
/* 718 */     WyRegistry.registerAbility(LeapAbility.INSTANCE);
/* 719 */     WyRegistry.registerAbility(StealPunchAbility.INSTANCE);
/* 720 */     WyRegistry.registerAbility(WeaponSpinAbility.INSTANCE);
/* 721 */     WyRegistry.registerAbility(KnockdownAbility.INSTANCE);
/* 722 */     WyRegistry.registerAbility(EmptyHandsAbility.INSTANCE);
/* 723 */     WyRegistry.registerAbility(TakedownKickAbility.INSTANCE);
/* 724 */     WyRegistry.registerAbility(TailSpinAbility.INSTANCE);
/* 725 */     WyRegistry.registerAbility(PearlFireAbility.INSTANCE);
/* 726 */     WyRegistry.registerAbility(StealthFootAbility.INSTANCE);
/* 727 */     WyRegistry.registerAbility(ShakushiAbility.INSTANCE);
/* 728 */     WyRegistry.registerAbility(BakudanAbility.INSTANCE);
/* 729 */     WyRegistry.registerAbility(MH5Ability.INSTANCE);
/* 730 */     WyRegistry.registerAbility(WootzNetLauncherAbility.INSTANCE);
/* 731 */     WyRegistry.registerAbility(SablesGuardAbility.INSTANCE);
/* 732 */     WyRegistry.registerAbility(GroundSeccoAbility.INSTANCE);
/* 733 */     WyRegistry.registerAbility(GrabLockAbility.INSTANCE);
/* 734 */     WyRegistry.registerAbility(HookGrabAbility.INSTANCE);
/* 735 */     WyRegistry.registerAbility(BombThrowAbility.INSTANCE);
/* 736 */     WyRegistry.registerAbility(HonkAbility.INSTANCE);
/* 737 */     WyRegistry.registerAbility(OneTwoJangoAbility.INSTANCE);
/* 738 */     WyRegistry.registerAbility(BattoStrikeAbility.INSTANCE);
/*     */     
/* 740 */     if (WyDebug.isDebug()) {
/* 741 */       WyRegistry.registerAbility(TestAbility.INSTANCE);
/* 742 */       WyRegistry.registerAbility(Test2Ability.INSTANCE);
/* 743 */       WyRegistry.registerAbility(Test3Ability.INSTANCE);
/*     */     } 
/*     */   }
/*     */ }


/* Location:              C:\Users\herrc\Downloads\mine-mine-no-mi-1.16.5-0.10.8.jar!\xyz\pixelatedw\mineminenomi\init\ModAbilities.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.1.3
 */