/*     */ package xyz.pixelatedw.mineminenomi.init;
/*     */ 
/*     */ import net.minecraft.util.HandSide;
/*     */ import net.minecraft.util.ResourceLocation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.BattoStrikeAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.BellyFlopAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.BodyRotateAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.BodyRotateWideArmsAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.CannonHandlingAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.CaughtInNetAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.ChargeCleaveAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.ChargeNetThrowAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.ChargePunchAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.CrossedArmAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.CrossedArmsAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.CrossedAttackAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.HandStandSpinAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.HandcuffedAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.LowSwingArmsAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.LoweringArmAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.OneTwoJangoAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.PitchSpinAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.PlayDeadAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.PointArmAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.PointArmsAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.PointWeaponAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.PunchRushAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.RaiseArmAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.RaiseArmsAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.RideStrikerAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.ShootSelfForwardAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.SpecialFlyAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.SpinToWinAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.TackleAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.TakedownKickAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.ThrowChakramAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.ThrowSpearAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.UnconsciousAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.UnconsciousYamchaAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.UnicycleRidingAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.WeaponSlamAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.WeaponStabDownAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.brawler.RyuNoIbukiAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.donkrieg.MH5Animation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.fishmen.SharkOnToothAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.gomu.GomuBazookaAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.gomu.GomuDawnWhipAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.gura.KaishinAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.kilo.KiloPressAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.mandemontactics.DemonicDanceChargeAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.mandemontactics.DemonicDanceLeapAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.mandemontactics.DemonicDashAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.mandemontactics.DemonicSmashAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.oto.BonAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.oto.DonAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.oto.ShanAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.pacifista.HeadLaserChargeAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.pteranodon.PteraAssaultFlyAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.pteranodon.PteraOpenMouthAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.sniper.AimSniperAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.suna.BarjanAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.supa.SparklingDaisyChargeAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.swordsman.CannonSlashAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.swordsman.IttoryuChargeAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.swordsman.UpperSlashAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.tori.PhoenixAssaultFlyAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.animations.tori.PhoenixKickAnimation;
/*     */ import xyz.pixelatedw.mineminenomi.api.animations.Animation;
/*     */ import xyz.pixelatedw.mineminenomi.api.animations.AnimationId;
/*     */ 
/*     */ public class ModAnimations
/*     */ {
/*  73 */   public static final AnimationId<CrossedArmsAnimation> CROSSED_ARMS = register("crossed_arms");
/*  74 */   public static final AnimationId<CrossedArmAnimation> CROSSED_LEFT_ARM = register("crossed_left_arm");
/*  75 */   public static final AnimationId<CrossedArmAnimation> CROSSED_RIGHT_ARM = register("crossed_right_arm");
/*  76 */   public static final AnimationId<HandStandSpinAnimation> HAND_STAND_SPIN = register("hand_stand_spin");
/*  77 */   public static final AnimationId<PitchSpinAnimation> PITCH_SPIN = register("pitch_spin");
/*  78 */   public static final AnimationId<BodyRotateAnimation> YAW_SPIN = register("yaw_spin");
/*  79 */   public static final AnimationId<PlayDeadAnimation> PLAY_DEAD = register("play_dead");
/*  80 */   public static final AnimationId<AimSniperAnimation> AIM_SNIPER = register("aim_sniper");
/*  81 */   public static final AnimationId<PunchRushAnimation> PUNCH_RUSH = register("punch_rush");
/*  82 */   public static final AnimationId<GomuBazookaAnimation> GOMU_BAZOOKA = register("gomu_bazooka");
/*  83 */   public static final AnimationId<CannonHandlingAnimation> CANNON_HANDLING = register("cannon_handling");
/*  84 */   public static final AnimationId<BodyRotateWideArmsAnimation> BODY_ROTATION_WIDE_ARMS = register("body_rotation_wide_arms");
/*  85 */   public static final AnimationId<ChargeCleaveAnimation> CHARGE_CLEAVE = register("charge_cleave");
/*  86 */   public static final AnimationId<ChargePunchAnimation> CHARGE_PUNCH = register("charge_punch");
/*  87 */   public static final AnimationId<HandcuffedAnimation> HANDCUFFED = register("handcuffed");
/*  88 */   public static final AnimationId<PointArmsAnimation> POINT_ARMS = register("point_arms");
/*  89 */   public static final AnimationId<PointArmAnimation> POINT_LEFT_ARM = register("point_left_arm");
/*  90 */   public static final AnimationId<PointArmAnimation> POINT_RIGHT_ARM = register("point_right_arm");
/*  91 */   public static final AnimationId<RaiseArmsAnimation> RAISE_ARMS = register("raise_arms");
/*  92 */   public static final AnimationId<RaiseArmAnimation> RAISE_LEFT_ARM = register("raise_left_arm");
/*  93 */   public static final AnimationId<RaiseArmAnimation> RAISE_RIGHT_ARM = register("raise_right_arm");
/*  94 */   public static final AnimationId<LowSwingArmsAnimation> LOW_SWING_ARMS = register("low_swing_arms");
/*  95 */   public static final AnimationId<SpecialFlyAnimation> SPECIAL_FLY = register("special_fly");
/*  96 */   public static final AnimationId<RideStrikerAnimation> RIDE_STRIKER = register("ride_striker");
/*  97 */   public static final AnimationId<ThrowSpearAnimation> THROW_SPEAR = register("throw_spear");
/*  98 */   public static final AnimationId<PointWeaponAnimation> POINT_WEAPON = register("point_weapon");
/*  99 */   public static final AnimationId<PteraAssaultFlyAnimation> PTERA_ASSAULT_FLY = register("ptera_assault_fly");
/* 100 */   public static final AnimationId<PteraOpenMouthAnimation> PTERA_OPEN_MOUTH = register("ptera_open_mouth");
/* 101 */   public static final AnimationId<CannonSlashAnimation> CANNON_SLASH = register("cannon_slash");
/* 102 */   public static final AnimationId<IttoryuChargeAnimation> ITTORYU_CHARGE = register("ittoryu_charge");
/* 103 */   public static final AnimationId<UpperSlashAnimation> UPPER_SLASH = register("upper_slash");
/* 104 */   public static final AnimationId<SparklingDaisyChargeAnimation> SPARKLING_DAISY_CHARGE = register("sparkling_daisy_charge");
/* 105 */   public static final AnimationId<KaishinAnimation> KAISHIN = register("kaishin");
/* 106 */   public static final AnimationId<BonAnimation> BON = register("bon");
/* 107 */   public static final AnimationId<DonAnimation> DON = register("don");
/* 108 */   public static final AnimationId<ShanAnimation> SHAN = register("shan");
/* 109 */   public static final AnimationId<PhoenixAssaultFlyAnimation> PHOENIX_ASSAULT_FLY = register("phoenix_assault_fly");
/* 110 */   public static final AnimationId<PhoenixKickAnimation> PHOENIX_KICK = register("phoenix_kick");
/* 111 */   public static final AnimationId<KiloPressAnimation> KILO_PRESS = register("kilo_press");
/* 112 */   public static final AnimationId<LoweringArmAnimation> LOWERING_RIGHT_ARM = register("lowering_right_arm");
/* 113 */   public static final AnimationId<TackleAnimation> TACKLE = register("tackle");
/* 114 */   public static final AnimationId<BellyFlopAnimation> BELLY_FLOP = register("belly_flop");
/* 115 */   public static final AnimationId<WeaponSlamAnimation> WEAPON_SLAM = register("weapon_slam");
/* 116 */   public static final AnimationId<SpinToWinAnimation> SPIN_TO_WIN = register("spin_to_win");
/* 117 */   public static final AnimationId<TakedownKickAnimation> TAKEDOWN_KICK = register("takedown_kick");
/* 118 */   public static final AnimationId<HeadLaserChargeAnimation> HEAD_LASER_CHARGE = register("head_laser_charge");
/* 119 */   public static final AnimationId<SharkOnToothAnimation> SHARK_ON_TOOTH = register("shark_on_tooth");
/* 120 */   public static final AnimationId<BarjanAnimation> BARJAN = register("barjan");
/* 121 */   public static final AnimationId<DemonicDanceChargeAnimation> DEMONIC_DANCE_CHARGE = register("demonic_dance_charge");
/* 122 */   public static final AnimationId<DemonicDanceLeapAnimation> DEMONIC_DANCE_LEAP = register("demonic_dance_leap");
/* 123 */   public static final AnimationId<DemonicSmashAnimation> DEMONIC_SMASH = register("demonic_smash");
/* 124 */   public static final AnimationId<DemonicDashAnimation> DEMONIC_DASH = register("demonic_dash");
/* 125 */   public static final AnimationId<CrossedAttackAnimation> CROSSED_ATTACK = register("crossed_attack");
/* 126 */   public static final AnimationId<ShootSelfForwardAnimation> SHOOT_SELF_FORWARD = register("shoot_self_forward");
/* 127 */   public static final AnimationId<MH5Animation> MH5_CHARGING = register("mh5_charging");
/* 128 */   public static final AnimationId<CaughtInNetAnimation> CAUGHT_IN_NET = register("caught_in_net");
/* 129 */   public static final AnimationId<GomuDawnWhipAnimation> GOMU_DAWN_WHIP = register("gomu_dawn_whip");
/* 130 */   public static final AnimationId<ChargeNetThrowAnimation> CHARGE_NET_THROW = register("charge_net_throw");
/* 131 */   public static final AnimationId<UnconsciousAnimation> UNCONSCIOUS = register("unconscious");
/* 132 */   public static final AnimationId<UnconsciousYamchaAnimation> UNCONSCIOUS_YAMCHA = register("unconscious_yamcha");
/* 133 */   public static final AnimationId<UnicycleRidingAnimation> RIDE_UNICYCLE = register("ride_unicycle");
/* 134 */   public static final AnimationId<WeaponStabDownAnimation> STAB_DOWN = register("stab_down");
/* 135 */   public static final AnimationId<OneTwoJangoAnimation> ONE_TWO_JANGO = register("one_two_jango");
/* 136 */   public static final AnimationId<RyuNoIbukiAnimation> RYU_NO_IBUKI = register("ryu_no_ibuki");
/* 137 */   public static final AnimationId<BattoStrikeAnimation> BATTO_STRIKE = register("batto_strike");
/* 138 */   public static final AnimationId<ThrowChakramAnimation> THROW_CHAKRAM = register("throw_chakram");
/*     */   
/*     */   private static <A extends Animation<?, ?>> AnimationId<A> register(String name) {
/* 141 */     return new AnimationId(new ResourceLocation("mineminenomi", name));
/*     */   }
/*     */   
/*     */   public static void clientInit() {
/* 145 */     AnimationId.register((Animation)new CrossedArmsAnimation(CROSSED_ARMS));
/* 146 */     AnimationId.register((Animation)new CrossedArmAnimation(CROSSED_LEFT_ARM, HandSide.LEFT));
/* 147 */     AnimationId.register((Animation)new CrossedArmAnimation(CROSSED_RIGHT_ARM, HandSide.RIGHT));
/* 148 */     AnimationId.register((Animation)new HandStandSpinAnimation(HAND_STAND_SPIN));
/* 149 */     AnimationId.register((Animation)new PitchSpinAnimation(PITCH_SPIN));
/* 150 */     AnimationId.register((Animation)new BodyRotateAnimation(YAW_SPIN, 40.0F));
/* 151 */     AnimationId.register((Animation)new PlayDeadAnimation(PLAY_DEAD));
/* 152 */     AnimationId.register((Animation)new AimSniperAnimation(AIM_SNIPER));
/* 153 */     AnimationId.register((Animation)new PunchRushAnimation(PUNCH_RUSH));
/* 154 */     AnimationId.register((Animation)new GomuBazookaAnimation(GOMU_BAZOOKA));
/* 155 */     AnimationId.register((Animation)new CannonHandlingAnimation(CANNON_HANDLING));
/* 156 */     AnimationId.register((Animation)new BodyRotateWideArmsAnimation(BODY_ROTATION_WIDE_ARMS, -40.0F));
/* 157 */     AnimationId.register((Animation)new ChargeCleaveAnimation(CHARGE_CLEAVE));
/* 158 */     AnimationId.register((Animation)new ChargePunchAnimation(CHARGE_PUNCH));
/* 159 */     AnimationId.register((Animation)new HandcuffedAnimation(HANDCUFFED));
/* 160 */     AnimationId.register((Animation)new PointArmsAnimation(POINT_ARMS));
/* 161 */     AnimationId.register((Animation)new PointArmAnimation(POINT_LEFT_ARM, HandSide.LEFT));
/* 162 */     AnimationId.register((Animation)new PointArmAnimation(POINT_RIGHT_ARM, HandSide.RIGHT));
/* 163 */     AnimationId.register((Animation)new RaiseArmsAnimation(RAISE_ARMS));
/* 164 */     AnimationId.register((Animation)new RaiseArmAnimation(RAISE_LEFT_ARM, HandSide.LEFT));
/* 165 */     AnimationId.register((Animation)new RaiseArmAnimation(RAISE_RIGHT_ARM, HandSide.RIGHT));
/* 166 */     AnimationId.register((Animation)new LowSwingArmsAnimation(LOW_SWING_ARMS));
/* 167 */     AnimationId.register((Animation)new SpecialFlyAnimation(SPECIAL_FLY));
/* 168 */     AnimationId.register((Animation)new RideStrikerAnimation(RIDE_STRIKER));
/* 169 */     AnimationId.register((Animation)new ThrowSpearAnimation(THROW_SPEAR));
/* 170 */     AnimationId.register((Animation)new PointWeaponAnimation(POINT_WEAPON));
/* 171 */     AnimationId.register((Animation)new PteraAssaultFlyAnimation(PTERA_ASSAULT_FLY));
/* 172 */     AnimationId.register((Animation)new PteraOpenMouthAnimation(PTERA_OPEN_MOUTH));
/* 173 */     AnimationId.register((Animation)new CannonSlashAnimation(CANNON_SLASH));
/* 174 */     AnimationId.register((Animation)new IttoryuChargeAnimation(ITTORYU_CHARGE));
/* 175 */     AnimationId.register((Animation)new UpperSlashAnimation(UPPER_SLASH));
/* 176 */     AnimationId.register((Animation)new SparklingDaisyChargeAnimation(SPARKLING_DAISY_CHARGE));
/* 177 */     AnimationId.register((Animation)new KaishinAnimation(KAISHIN));
/* 178 */     AnimationId.register((Animation)new BonAnimation(BON));
/* 179 */     AnimationId.register((Animation)new DonAnimation(DON));
/* 180 */     AnimationId.register((Animation)new ShanAnimation(SHAN));
/* 181 */     AnimationId.register((Animation)new PhoenixAssaultFlyAnimation(PHOENIX_ASSAULT_FLY));
/* 182 */     AnimationId.register((Animation)new PhoenixKickAnimation(PHOENIX_KICK));
/* 183 */     AnimationId.register((Animation)new KiloPressAnimation(KILO_PRESS));
/* 184 */     AnimationId.register((Animation)new LoweringArmAnimation(LOWERING_RIGHT_ARM));
/* 185 */     AnimationId.register((Animation)new TackleAnimation(TACKLE, HandSide.RIGHT));
/* 186 */     AnimationId.register((Animation)new BellyFlopAnimation(BELLY_FLOP));
/* 187 */     AnimationId.register((Animation)new WeaponSlamAnimation(WEAPON_SLAM));
/* 188 */     AnimationId.register((Animation)new SpinToWinAnimation(SPIN_TO_WIN, -40.0F));
/* 189 */     AnimationId.register((Animation)new TakedownKickAnimation(TAKEDOWN_KICK));
/* 190 */     AnimationId.register((Animation)new HeadLaserChargeAnimation(HEAD_LASER_CHARGE));
/* 191 */     AnimationId.register((Animation)new SharkOnToothAnimation(SHARK_ON_TOOTH));
/* 192 */     AnimationId.register((Animation)new BarjanAnimation(BARJAN));
/* 193 */     AnimationId.register((Animation)new DemonicDanceChargeAnimation(DEMONIC_DANCE_CHARGE));
/* 194 */     AnimationId.register((Animation)new DemonicDanceLeapAnimation(DEMONIC_DANCE_LEAP));
/* 195 */     AnimationId.register((Animation)new DemonicSmashAnimation(DEMONIC_SMASH));
/* 196 */     AnimationId.register((Animation)new DemonicDashAnimation(DEMONIC_DASH));
/* 197 */     AnimationId.register((Animation)new CrossedAttackAnimation(CROSSED_ATTACK));
/* 198 */     AnimationId.register((Animation)new ShootSelfForwardAnimation(SHOOT_SELF_FORWARD));
/* 199 */     AnimationId.register((Animation)new MH5Animation(MH5_CHARGING));
/* 200 */     AnimationId.register((Animation)new CaughtInNetAnimation(CAUGHT_IN_NET));
/* 201 */     AnimationId.register((Animation)new GomuDawnWhipAnimation(GOMU_DAWN_WHIP));
/* 202 */     AnimationId.register((Animation)new ChargeNetThrowAnimation(CHARGE_NET_THROW));
/* 203 */     AnimationId.register((Animation)new UnconsciousAnimation(UNCONSCIOUS));
/* 204 */     AnimationId.register((Animation)new UnconsciousYamchaAnimation(UNCONSCIOUS_YAMCHA));
/* 205 */     AnimationId.register((Animation)new UnicycleRidingAnimation(RIDE_UNICYCLE));
/* 206 */     AnimationId.register((Animation)new WeaponStabDownAnimation(STAB_DOWN));
/* 207 */     AnimationId.register((Animation)new OneTwoJangoAnimation(ONE_TWO_JANGO));
/* 208 */     AnimationId.register((Animation)new RyuNoIbukiAnimation(RYU_NO_IBUKI));
/* 209 */     AnimationId.register((Animation)new BattoStrikeAnimation(BATTO_STRIKE));
/* 210 */     AnimationId.register((Animation)new ThrowChakramAnimation(THROW_CHAKRAM));
/*     */   }
/*     */ }


/* Location:              C:\Users\herrc\Downloads\mine-mine-no-mi-1.16.5-0.10.8.jar!\xyz\pixelatedw\mineminenomi\init\ModAnimations.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.1.3
 */