/*     */ package xyz.pixelatedw.mineminenomi.init;
/*     */ 
/*     */ import xyz.pixelatedw.mineminenomi.packets.client.CFinishCCPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.client.CRequestSyncAbilityDataPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.client.CRequestSyncQuestDataPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.client.ability.CEquipAbilityPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.client.ability.CRemoveAbilityPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.client.ability.CSetCombatBarPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.client.ability.CSetHakiColorPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.client.ability.CToggleCombatModePacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.client.ability.CTogglePassiveAbilityPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.client.ability.CUseAbilityPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.client.ability.components.CChangeAbilityAltModePacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.client.ability.components.CSwingTriggerPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.client.challenge.CAcceptChallengeInvitationPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.client.challenge.CDisbandChallengeGroupPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.client.challenge.CResetChallengesPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.client.challenge.CSendChallengeInvitationPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.client.challenge.CStartChallengePacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.client.crew.CCreateCrewPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.client.crew.CKickFromCrewPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.client.crew.CLeaveCrewPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.client.crew.CUpdateJollyRogerPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.client.entities.CUpdateInventoryPagePacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.client.entity.CDoctorHealPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.client.entity.CSwitchVehicleModePacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.client.entity.CSyncPlayerInputPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.client.ofpw.CRequestCreativeDeleteOFPWPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.client.ofpw.CRequestCreativeSpawnOFPWPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.client.quest.CAbandonQuestPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.client.quest.CStartObjectiveEventPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.client.quest.CUpdateQuestStatePacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.client.trade.CBuyFromTraderPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.client.trade.CSellToTraderPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.client.ui.COpenChallengesScreenPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.client.ui.COpenCrewScreenPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.client.ui.COpenJollyRogerCreatorScreenPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.client.ui.COpenPlayerScreenPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.client.ui.CScreenEventPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.client.ui.CTriggerInteractionPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.SAddScreenShaderPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.SCarryEntityPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.SFlightValuePacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.SFlySpeedPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.SGrabScreenshotPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.SLeashPlayerPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.SRemoveAttributePacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.SRemoveScreenShaderPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.SSetEffectDetailsPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.SSetFlagOnFirePacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.SSetRogueModePacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.SSetServerMaxBarsPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.SSpawnParticleEffectPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.SStepHeightValuePacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.SSyncAbilityDataPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.SSyncChallengeDataPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.SSyncDevilFruitPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.SSyncDynDimensionsPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.SSyncEntityStatsPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.SSyncHakiDataPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.SSyncProjectileExtrasPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.SSyncQuestDataPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.SSyncStrikerCrewPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.SToggleAnimationPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.SUpdateCombatStatePacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ability.SAnimeScreamPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ability.SEquipAbilityPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ability.SRecalculateEyeHeightPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ability.SSetCombatBarPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ability.SSetHakiColorPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ability.SStartGCDPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ability.SSyncAbilityPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ability.SToggleCombatModePacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ability.SToggleDrumsOfLiberationSoundPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ability.SUpdateAbilityIconPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ability.SUpdateAbilityTimeProgressionPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ability.SUpdateEquippedAbilityPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ability.SUpdateEquippedAbilityPacket2;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ability.SUpdateExtraDataPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ability.SUpdateHakiColorPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ability.SUpdatePassiveAbilityDataPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ability.SUseAbilityPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ability.SViewProtectionPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ability.components.SBonusManagerUpdatePacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ability.components.SChangeAbilityAltModePacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ability.components.SChangeAbilitySwitchModePacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ability.components.SChangeAnimationStatePacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ability.components.SChangeMorphPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ability.components.SDisableAbilityPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ability.components.SForceStopChargingPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ability.components.SSetContinuityThresholdPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ability.components.SSetOverlayLayersPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ability.components.SSetPauseTickPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ability.components.SSetPoolInUsePacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ability.components.SSetStacksPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ability.components.SStartChargingPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ability.components.SStartContinuityPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ability.components.SStartCooldownPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ability.components.SStartDisablePacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ability.components.SStopChargingPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ability.components.SStopContinuityPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ability.components.SStopCooldownPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ability.components.SStopDisablePacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ability.components.SSwingTriggerPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.animations.SSetNPCTimeAnimationPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.challenge.SUpdateChallengeGroupPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.entities.SKairosekiCoatingPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.entities.SPinCameraPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.entities.SUnpinCameraPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.entities.SUpdateColaAmountPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.entities.SUpdateEntityOwnerPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.entities.SUpdateLightningEntity;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.entities.SUpdateProjBlockCollisionBox;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.entities.SUpdateProjEntityCollisionBox;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.quest.SDespawnQuestObjectivePacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.quest.SFinishObjectivePacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.randfruit.SSetFruitSeedsPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.randfruit.SSetRandomizedFruitsPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.trade.SUpdateTraderOffersPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ui.SCloseScreenPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ui.SOpenAbilitySelectionScreenPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ui.SOpenArenaSetupScreenPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ui.SOpenChallengeGroupSelectorPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ui.SOpenChallengesScreenPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ui.SOpenCharacterCreatorScreenPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ui.SOpenCrewScreenPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ui.SOpenDialogueScreenPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ui.SOpenEncyclopediaScreenPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ui.SOpenJollyRogerCreatorScreenPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ui.SOpenNewCrewScreenPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ui.SOpenPlayerScreenPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ui.SOpenQuestChooseScreenPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ui.SOpenQuestTrackerScreenPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ui.SOpenTraderScreenPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ui.SOpenWantedPosterScreenPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ui.STriggerInteractionPacket;
/*     */ import xyz.pixelatedw.mineminenomi.packets.server.ui.SUpdateOPBossInfoPacket;
/*     */ import xyz.pixelatedw.mineminenomi.wypi.WyNetwork;
/*     */ 
/*     */ public class ModNetwork
/*     */ {
/*     */   public static void init() {
/* 143 */     WyNetwork.registerPacket(CUpdateQuestStatePacket.class, CUpdateQuestStatePacket::encode, CUpdateQuestStatePacket::decode, CUpdateQuestStatePacket::handle);
/* 144 */     WyNetwork.registerPacket(CToggleCombatModePacket.class, CToggleCombatModePacket::encode, CToggleCombatModePacket::decode, CToggleCombatModePacket::handle);
/* 145 */     WyNetwork.registerPacket(CUseAbilityPacket.class, CUseAbilityPacket::encode, CUseAbilityPacket::decode, CUseAbilityPacket::handle);
/* 146 */     WyNetwork.registerPacket(CFinishCCPacket.class, CFinishCCPacket::encode, CFinishCCPacket::decode, CFinishCCPacket::handle);
/* 147 */     WyNetwork.registerPacket(CRequestSyncQuestDataPacket.class, CRequestSyncQuestDataPacket::encode, CRequestSyncQuestDataPacket::decode, CRequestSyncQuestDataPacket::handle);
/* 148 */     WyNetwork.registerPacket(CRemoveAbilityPacket.class, CRemoveAbilityPacket::encode, CRemoveAbilityPacket::decode, CRemoveAbilityPacket::handle);
/* 149 */     WyNetwork.registerPacket(CCreateCrewPacket.class, CCreateCrewPacket::encode, CCreateCrewPacket::decode, CCreateCrewPacket::handle);
/* 150 */     WyNetwork.registerPacket(CLeaveCrewPacket.class, CLeaveCrewPacket::encode, CLeaveCrewPacket::decode, CLeaveCrewPacket::handle);
/* 151 */     WyNetwork.registerPacket(CUpdateJollyRogerPacket.class, CUpdateJollyRogerPacket::encode, CUpdateJollyRogerPacket::decode, CUpdateJollyRogerPacket::handle);
/* 152 */     WyNetwork.registerPacket(CSetCombatBarPacket.class, CSetCombatBarPacket::encode, CSetCombatBarPacket::decode, CSetCombatBarPacket::handle);
/* 153 */     WyNetwork.registerPacket(CStartChallengePacket.class, CStartChallengePacket::encode, CStartChallengePacket::decode, CStartChallengePacket::handle);
/* 154 */     WyNetwork.registerPacket(CResetChallengesPacket.class, CResetChallengesPacket::encode, CResetChallengesPacket::decode, CResetChallengesPacket::handle);
/* 155 */     WyNetwork.registerPacket(CKickFromCrewPacket.class, CKickFromCrewPacket::encode, CKickFromCrewPacket::decode, CKickFromCrewPacket::handle);
/* 156 */     WyNetwork.registerPacket(CStartObjectiveEventPacket.class, CStartObjectiveEventPacket::encode, CStartObjectiveEventPacket::decode, CStartObjectiveEventPacket::handle);
/* 157 */     WyNetwork.registerPacket(CAbandonQuestPacket.class, CAbandonQuestPacket::encode, CAbandonQuestPacket::decode, CAbandonQuestPacket::handle);
/* 158 */     WyNetwork.registerPacket(CSellToTraderPacket.class, CSellToTraderPacket::encode, CSellToTraderPacket::decode, CSellToTraderPacket::handle);
/* 159 */     WyNetwork.registerPacket(CBuyFromTraderPacket.class, CBuyFromTraderPacket::encode, CBuyFromTraderPacket::decode, CBuyFromTraderPacket::handle);
/* 160 */     WyNetwork.registerPacket(CEquipAbilityPacket.class, CEquipAbilityPacket::encode, CEquipAbilityPacket::decode, CEquipAbilityPacket::handle);
/* 161 */     WyNetwork.registerPacket(CTogglePassiveAbilityPacket.class, CTogglePassiveAbilityPacket::encode, CTogglePassiveAbilityPacket::decode, CTogglePassiveAbilityPacket::handle);
/* 162 */     WyNetwork.registerPacket(COpenPlayerScreenPacket.class, COpenPlayerScreenPacket::encode, COpenPlayerScreenPacket::decode, COpenPlayerScreenPacket::handle);
/* 163 */     WyNetwork.registerPacket(COpenChallengesScreenPacket.class, COpenChallengesScreenPacket::encode, COpenChallengesScreenPacket::decode, COpenChallengesScreenPacket::handle);
/* 164 */     WyNetwork.registerPacket(CRequestSyncAbilityDataPacket.class, CRequestSyncAbilityDataPacket::encode, CRequestSyncAbilityDataPacket::decode, CRequestSyncAbilityDataPacket::handle);
/* 165 */     WyNetwork.registerPacket(CSetHakiColorPacket.class, CSetHakiColorPacket::encode, CSetHakiColorPacket::decode, CSetHakiColorPacket::handle);
/* 166 */     WyNetwork.registerPacket(CRequestCreativeDeleteOFPWPacket.class, CRequestCreativeDeleteOFPWPacket::encode, CRequestCreativeDeleteOFPWPacket::decode, CRequestCreativeDeleteOFPWPacket::handle);
/* 167 */     WyNetwork.registerPacket(CRequestCreativeSpawnOFPWPacket.class, CRequestCreativeSpawnOFPWPacket::encode, CRequestCreativeSpawnOFPWPacket::decode, CRequestCreativeSpawnOFPWPacket::handle);
/* 168 */     WyNetwork.registerPacket(CUpdateInventoryPagePacket.class, CUpdateInventoryPagePacket::encode, CUpdateInventoryPagePacket::decode, CUpdateInventoryPagePacket::handle);
/* 169 */     WyNetwork.registerPacket(CDoctorHealPacket.class, CDoctorHealPacket::encode, CDoctorHealPacket::decode, CDoctorHealPacket::handle);
/* 170 */     WyNetwork.registerPacket(CSwitchVehicleModePacket.class, CSwitchVehicleModePacket::encode, CSwitchVehicleModePacket::decode, CSwitchVehicleModePacket::handle);
/* 171 */     WyNetwork.registerPacket(CSendChallengeInvitationPacket.class, CSendChallengeInvitationPacket::encode, CSendChallengeInvitationPacket::decode, CSendChallengeInvitationPacket::handle);
/* 172 */     WyNetwork.registerPacket(CAcceptChallengeInvitationPacket.class, CAcceptChallengeInvitationPacket::encode, CAcceptChallengeInvitationPacket::decode, CAcceptChallengeInvitationPacket::handle);
/* 173 */     WyNetwork.registerPacket(CDisbandChallengeGroupPacket.class, CDisbandChallengeGroupPacket::encode, CDisbandChallengeGroupPacket::decode, CDisbandChallengeGroupPacket::handle);
/* 174 */     WyNetwork.registerPacket(CScreenEventPacket.class, CScreenEventPacket::encode, CScreenEventPacket::decode, CScreenEventPacket::handle);
/* 175 */     WyNetwork.registerPacket(COpenCrewScreenPacket.class, COpenCrewScreenPacket::encode, COpenCrewScreenPacket::decode, COpenCrewScreenPacket::handle);
/* 176 */     WyNetwork.registerPacket(CSyncPlayerInputPacket.class, CSyncPlayerInputPacket::encode, CSyncPlayerInputPacket::decode, CSyncPlayerInputPacket::handle);
/* 177 */     WyNetwork.registerPacket(COpenJollyRogerCreatorScreenPacket.class, COpenJollyRogerCreatorScreenPacket::encode, COpenJollyRogerCreatorScreenPacket::decode, COpenJollyRogerCreatorScreenPacket::handle);
/* 178 */     WyNetwork.registerPacket(CTriggerInteractionPacket.class, CTriggerInteractionPacket::encode, CTriggerInteractionPacket::decode, CTriggerInteractionPacket::handle);
/*     */ 
/*     */     
/* 181 */     WyNetwork.registerPacket(CChangeAbilityAltModePacket.class, CChangeAbilityAltModePacket::encode, CChangeAbilityAltModePacket::decode, CChangeAbilityAltModePacket::handle);
/* 182 */     WyNetwork.registerPacket(CSwingTriggerPacket.class, CSwingTriggerPacket::encode, CSwingTriggerPacket::decode, CSwingTriggerPacket::handle);
/*     */ 
/*     */     
/* 185 */     WyNetwork.registerPacket(SSyncAbilityDataPacket.class, SSyncAbilityDataPacket::encode, SSyncAbilityDataPacket::decode, SSyncAbilityDataPacket::handle);
/* 186 */     WyNetwork.registerPacket(SSyncQuestDataPacket.class, SSyncQuestDataPacket::encode, SSyncQuestDataPacket::decode, SSyncQuestDataPacket::handle);
/* 187 */     WyNetwork.registerPacket(SSyncDevilFruitPacket.class, SSyncDevilFruitPacket::encode, SSyncDevilFruitPacket::decode, SSyncDevilFruitPacket::handle);
/* 188 */     WyNetwork.registerPacket(SSyncEntityStatsPacket.class, SSyncEntityStatsPacket::encode, SSyncEntityStatsPacket::decode, SSyncEntityStatsPacket::handle);
/* 189 */     WyNetwork.registerPacket(SFlySpeedPacket.class, SFlySpeedPacket::encode, SFlySpeedPacket::decode, SFlySpeedPacket::handle);
/* 190 */     WyNetwork.registerPacket(SRecalculateEyeHeightPacket.class, SRecalculateEyeHeightPacket::encode, SRecalculateEyeHeightPacket::decode, SRecalculateEyeHeightPacket::handle);
/* 191 */     WyNetwork.registerPacket(SViewProtectionPacket.class, SViewProtectionPacket::encode, SViewProtectionPacket::decode, SViewProtectionPacket::handle);
/* 192 */     WyNetwork.registerPacket(SOpenCharacterCreatorScreenPacket.class, SOpenCharacterCreatorScreenPacket::encode, SOpenCharacterCreatorScreenPacket::decode, SOpenCharacterCreatorScreenPacket::handle);
/* 193 */     WyNetwork.registerPacket(SOpenWantedPosterScreenPacket.class, SOpenWantedPosterScreenPacket::encode, SOpenWantedPosterScreenPacket::decode, SOpenWantedPosterScreenPacket::handle);
/* 194 */     WyNetwork.registerPacket(SDespawnQuestObjectivePacket.class, SDespawnQuestObjectivePacket::encode, SDespawnQuestObjectivePacket::decode, SDespawnQuestObjectivePacket::handle);
/* 195 */     WyNetwork.registerPacket(SUpdateTraderOffersPacket.class, SUpdateTraderOffersPacket::encode, SUpdateTraderOffersPacket::decode, SUpdateTraderOffersPacket::handle);
/* 196 */     WyNetwork.registerPacket(SOpenTraderScreenPacket.class, SOpenTraderScreenPacket::encode, SOpenTraderScreenPacket::decode, SOpenTraderScreenPacket::handle);
/* 197 */     WyNetwork.registerPacket(SOpenJollyRogerCreatorScreenPacket.class, SOpenJollyRogerCreatorScreenPacket::encode, SOpenJollyRogerCreatorScreenPacket::decode, SOpenJollyRogerCreatorScreenPacket::handle);
/* 198 */     WyNetwork.registerPacket(SOpenQuestChooseScreenPacket.class, SOpenQuestChooseScreenPacket::encode, SOpenQuestChooseScreenPacket::decode, SOpenQuestChooseScreenPacket::handle);
/* 199 */     WyNetwork.registerPacket(SOpenNewCrewScreenPacket.class, SOpenNewCrewScreenPacket::encode, SOpenNewCrewScreenPacket::decode, SOpenNewCrewScreenPacket::handle);
/* 200 */     WyNetwork.registerPacket(SSyncHakiDataPacket.class, SSyncHakiDataPacket::encode, SSyncHakiDataPacket::decode, SSyncHakiDataPacket::handle);
/* 201 */     WyNetwork.registerPacket(SFlightValuePacket.class, SFlightValuePacket::encode, SFlightValuePacket::decode, SFlightValuePacket::handle);
/* 202 */     WyNetwork.registerPacket(SSyncChallengeDataPacket.class, SSyncChallengeDataPacket::encode, SSyncChallengeDataPacket::decode, SSyncChallengeDataPacket::handle);
/* 203 */     WyNetwork.registerPacket(SAnimeScreamPacket.class, SAnimeScreamPacket::encode, SAnimeScreamPacket::decode, SAnimeScreamPacket::handle);
/* 204 */     WyNetwork.registerPacket(SUpdateEquippedAbilityPacket.class, SUpdateEquippedAbilityPacket::encode, SUpdateEquippedAbilityPacket::decode, SUpdateEquippedAbilityPacket::handle);
/* 205 */     WyNetwork.registerPacket(SOpenArenaSetupScreenPacket.class, SOpenArenaSetupScreenPacket::encode, SOpenArenaSetupScreenPacket::decode, SOpenArenaSetupScreenPacket::handle);
/* 206 */     WyNetwork.registerPacket(SCloseScreenPacket.class, SCloseScreenPacket::encode, SCloseScreenPacket::decode, SCloseScreenPacket::handle);
/* 207 */     WyNetwork.registerPacket(SSetEffectDetailsPacket.class, SSetEffectDetailsPacket::encode, SSetEffectDetailsPacket::decode, SSetEffectDetailsPacket::handle);
/* 208 */     WyNetwork.registerPacket(SUpdateEntityOwnerPacket.class, SUpdateEntityOwnerPacket::encode, SUpdateEntityOwnerPacket::decode, SUpdateEntityOwnerPacket::handle);
/* 209 */     WyNetwork.registerPacket(SOpenPlayerScreenPacket.class, SOpenPlayerScreenPacket::encode, SOpenPlayerScreenPacket::decode, SOpenPlayerScreenPacket::handle);
/* 210 */     WyNetwork.registerPacket(SSetCombatBarPacket.class, SSetCombatBarPacket::encode, SSetCombatBarPacket::decode, SSetCombatBarPacket::handle);
/* 211 */     WyNetwork.registerPacket(SOpenChallengesScreenPacket.class, SOpenChallengesScreenPacket::encode, SOpenChallengesScreenPacket::decode, SOpenChallengesScreenPacket::handle);
/* 212 */     WyNetwork.registerPacket(SSetRandomizedFruitsPacket.class, SSetRandomizedFruitsPacket::encode, SSetRandomizedFruitsPacket::decode, SSetRandomizedFruitsPacket::handle);
/* 213 */     WyNetwork.registerPacket(SSetFruitSeedsPacket.class, SSetFruitSeedsPacket::encode, SSetFruitSeedsPacket::decode, SSetFruitSeedsPacket::handle);
/* 214 */     WyNetwork.registerPacket(SOpenEncyclopediaScreenPacket.class, SOpenEncyclopediaScreenPacket::encode, SOpenEncyclopediaScreenPacket::decode, SOpenEncyclopediaScreenPacket::handle);
/* 215 */     WyNetwork.registerPacket(SUpdateAbilityTimeProgressionPacket.class, SUpdateAbilityTimeProgressionPacket::encode, SUpdateAbilityTimeProgressionPacket::decode, SUpdateAbilityTimeProgressionPacket::handle);
/* 216 */     WyNetwork.registerPacket(SStepHeightValuePacket.class, SStepHeightValuePacket::encode, SStepHeightValuePacket::decode, SStepHeightValuePacket::handle);
/* 217 */     WyNetwork.registerPacket(SOpenQuestTrackerScreenPacket.class, SOpenQuestTrackerScreenPacket::encode, SOpenQuestTrackerScreenPacket::decode, SOpenQuestTrackerScreenPacket::handle);
/* 218 */     WyNetwork.registerPacket(SUpdateExtraDataPacket.class, SUpdateExtraDataPacket::encode, SUpdateExtraDataPacket::decode, SUpdateExtraDataPacket::handle);
/* 219 */     WyNetwork.registerPacket(SUpdateAbilityIconPacket.class, SUpdateAbilityIconPacket::encode, SUpdateAbilityIconPacket::decode, SUpdateAbilityIconPacket::handle);
/* 220 */     WyNetwork.registerPacket(SOpenAbilitySelectionScreenPacket.class, SOpenAbilitySelectionScreenPacket::encode, SOpenAbilitySelectionScreenPacket::decode, SOpenAbilitySelectionScreenPacket::handle);
/* 221 */     WyNetwork.registerPacket(SSyncDynDimensionsPacket.class, SSyncDynDimensionsPacket::encode, SSyncDynDimensionsPacket::decode, SSyncDynDimensionsPacket::handle);
/* 222 */     WyNetwork.registerPacket(SSetHakiColorPacket.class, SSetHakiColorPacket::encode, SSetHakiColorPacket::decode, SSetHakiColorPacket::handle);
/* 223 */     WyNetwork.registerPacket(SRemoveAttributePacket.class, SRemoveAttributePacket::encode, SRemoveAttributePacket::decode, SRemoveAttributePacket::handle);
/* 224 */     WyNetwork.registerPacket(SToggleCombatModePacket.class, SToggleCombatModePacket::encode, SToggleCombatModePacket::decode, SToggleCombatModePacket::handle);
/* 225 */     WyNetwork.registerPacket(SSetNPCTimeAnimationPacket.class, SSetNPCTimeAnimationPacket::encode, SSetNPCTimeAnimationPacket::decode, SSetNPCTimeAnimationPacket::handle);
/* 226 */     WyNetwork.registerPacket(SDisableAbilityPacket.class, SDisableAbilityPacket::encode, SDisableAbilityPacket::decode, SDisableAbilityPacket::handle);
/* 227 */     WyNetwork.registerPacket(SSpawnParticleEffectPacket.class, SSpawnParticleEffectPacket::encode, SSpawnParticleEffectPacket::decode, SSpawnParticleEffectPacket::handle);
/* 228 */     WyNetwork.registerPacket(SUpdateOPBossInfoPacket.class, SUpdateOPBossInfoPacket::encode, SUpdateOPBossInfoPacket::decode, SUpdateOPBossInfoPacket::handle);
/* 229 */     WyNetwork.registerPacket(SSyncAbilityPacket.class, SSyncAbilityPacket::encode, SSyncAbilityPacket::decode, SSyncAbilityPacket::handle);
/* 230 */     WyNetwork.registerPacket(SUpdateEquippedAbilityPacket2.class, SUpdateEquippedAbilityPacket2::encode, SUpdateEquippedAbilityPacket2::decode, SUpdateEquippedAbilityPacket2::handle);
/* 231 */     WyNetwork.registerPacket(SEquipAbilityPacket.class, SEquipAbilityPacket::encode, SEquipAbilityPacket::decode, SEquipAbilityPacket::handle);
/* 232 */     WyNetwork.registerPacket(SStartGCDPacket.class, SStartGCDPacket::encode, SStartGCDPacket::decode, SStartGCDPacket::handle);
/* 233 */     WyNetwork.registerPacket(SSetFlagOnFirePacket.class, SSetFlagOnFirePacket::encode, SSetFlagOnFirePacket::decode, SSetFlagOnFirePacket::handle);
/* 234 */     WyNetwork.registerPacket(SUseAbilityPacket.class, SUseAbilityPacket::encode, SUseAbilityPacket::decode, SUseAbilityPacket::handle);
/* 235 */     WyNetwork.registerPacket(SGrabScreenshotPacket.class, SGrabScreenshotPacket::encode, SGrabScreenshotPacket::decode, SGrabScreenshotPacket::handle);
/* 236 */     WyNetwork.registerPacket(SUpdateColaAmountPacket.class, SUpdateColaAmountPacket::encode, SUpdateColaAmountPacket::decode, SUpdateColaAmountPacket::handle);
/* 237 */     WyNetwork.registerPacket(SUpdatePassiveAbilityDataPacket.class, SUpdatePassiveAbilityDataPacket::encode, SUpdatePassiveAbilityDataPacket::decode, SUpdatePassiveAbilityDataPacket::handle);
/* 238 */     WyNetwork.registerPacket(SUpdateCombatStatePacket.class, SUpdateCombatStatePacket::encode, SUpdateCombatStatePacket::decode, SUpdateCombatStatePacket::handle);
/* 239 */     WyNetwork.registerPacket(SSyncProjectileExtrasPacket.class, SSyncProjectileExtrasPacket::encode, SSyncProjectileExtrasPacket::decode, SSyncProjectileExtrasPacket::handle);
/* 240 */     WyNetwork.registerPacket(SCarryEntityPacket.class, SCarryEntityPacket::encode, SCarryEntityPacket::decode, SCarryEntityPacket::handle);
/* 241 */     WyNetwork.registerPacket(SLeashPlayerPacket.class, SLeashPlayerPacket::encode, SLeashPlayerPacket::decode, SLeashPlayerPacket::handle);
/* 242 */     WyNetwork.registerPacket(SUpdateChallengeGroupPacket.class, SUpdateChallengeGroupPacket::encode, SUpdateChallengeGroupPacket::decode, SUpdateChallengeGroupPacket::handle);
/* 243 */     WyNetwork.registerPacket(SOpenChallengeGroupSelectorPacket.class, SOpenChallengeGroupSelectorPacket::encode, SOpenChallengeGroupSelectorPacket::decode, SOpenChallengeGroupSelectorPacket::handle);
/* 244 */     WyNetwork.registerPacket(SUpdateProjEntityCollisionBox.class, SUpdateProjEntityCollisionBox::encode, SUpdateProjEntityCollisionBox::decode, SUpdateProjEntityCollisionBox::handle);
/* 245 */     WyNetwork.registerPacket(SUpdateProjBlockCollisionBox.class, SUpdateProjBlockCollisionBox::encode, SUpdateProjBlockCollisionBox::decode, SUpdateProjBlockCollisionBox::handle);
/* 246 */     WyNetwork.registerPacket(SUpdateLightningEntity.class, SUpdateLightningEntity::encode, SUpdateLightningEntity::decode, SUpdateLightningEntity::handle);
/* 247 */     WyNetwork.registerPacket(SOpenCrewScreenPacket.class, SOpenCrewScreenPacket::encode, SOpenCrewScreenPacket::decode, SOpenCrewScreenPacket::handle);
/* 248 */     WyNetwork.registerPacket(SUpdateHakiColorPacket.class, SUpdateHakiColorPacket::encode, SUpdateHakiColorPacket::decode, SUpdateHakiColorPacket::handle);
/* 249 */     WyNetwork.registerPacket(SToggleAnimationPacket.class, SToggleAnimationPacket::encode, SToggleAnimationPacket::decode, SToggleAnimationPacket::handle);
/* 250 */     WyNetwork.registerPacket(SAddScreenShaderPacket.class, SAddScreenShaderPacket::encode, SAddScreenShaderPacket::decode, SAddScreenShaderPacket::handle);
/* 251 */     WyNetwork.registerPacket(SRemoveScreenShaderPacket.class, SRemoveScreenShaderPacket::encode, SRemoveScreenShaderPacket::decode, SRemoveScreenShaderPacket::handle);
/* 252 */     WyNetwork.registerPacket(SFinishObjectivePacket.class, SFinishObjectivePacket::encode, SFinishObjectivePacket::decode, SFinishObjectivePacket::handle);
/* 253 */     WyNetwork.registerPacket(SSyncStrikerCrewPacket.class, SSyncStrikerCrewPacket::encode, SSyncStrikerCrewPacket::decode, SSyncStrikerCrewPacket::handle);
/* 254 */     WyNetwork.registerPacket(SKairosekiCoatingPacket.class, SKairosekiCoatingPacket::encode, SKairosekiCoatingPacket::decode, SKairosekiCoatingPacket::handle);
/* 255 */     WyNetwork.registerPacket(SOpenDialogueScreenPacket.class, SOpenDialogueScreenPacket::encode, SOpenDialogueScreenPacket::decode, SOpenDialogueScreenPacket::handle);
/* 256 */     WyNetwork.registerPacket(STriggerInteractionPacket.class, STriggerInteractionPacket::encode, STriggerInteractionPacket::decode, STriggerInteractionPacket::handle);
/* 257 */     WyNetwork.registerPacket(SSetServerMaxBarsPacket.class, SSetServerMaxBarsPacket::encode, SSetServerMaxBarsPacket::decode, SSetServerMaxBarsPacket::handle);
/* 258 */     WyNetwork.registerPacket(SSetRogueModePacket.class, SSetRogueModePacket::encode, SSetRogueModePacket::decode, SSetRogueModePacket::handle);
/* 259 */     WyNetwork.registerPacket(SPinCameraPacket.class, SPinCameraPacket::encode, SPinCameraPacket::decode, SPinCameraPacket::handle);
/* 260 */     WyNetwork.registerPacket(SUnpinCameraPacket.class, SUnpinCameraPacket::encode, SUnpinCameraPacket::decode, SUnpinCameraPacket::handle);
/* 261 */     WyNetwork.registerPacket(SToggleDrumsOfLiberationSoundPacket.class, SToggleDrumsOfLiberationSoundPacket::encode, SToggleDrumsOfLiberationSoundPacket::decode, SToggleDrumsOfLiberationSoundPacket::handle);
/*     */ 
/*     */     
/* 264 */     WyNetwork.registerPacket(SStartCooldownPacket.class, SStartCooldownPacket::encode, SStartCooldownPacket::decode, SStartCooldownPacket::handle);
/* 265 */     WyNetwork.registerPacket(SStopCooldownPacket.class, SStopCooldownPacket::encode, SStopCooldownPacket::decode, SStopCooldownPacket::handle);
/* 266 */     WyNetwork.registerPacket(SStartContinuityPacket.class, SStartContinuityPacket::encode, SStartContinuityPacket::decode, SStartContinuityPacket::handle);
/* 267 */     WyNetwork.registerPacket(SStopContinuityPacket.class, SStopContinuityPacket::encode, SStopContinuityPacket::decode, SStopContinuityPacket::handle);
/* 268 */     WyNetwork.registerPacket(SStartChargingPacket.class, SStartChargingPacket::encode, SStartChargingPacket::decode, SStartChargingPacket::handle);
/* 269 */     WyNetwork.registerPacket(SStopChargingPacket.class, SStopChargingPacket::encode, SStopChargingPacket::decode, SStopChargingPacket::handle);
/* 270 */     WyNetwork.registerPacket(SStartDisablePacket.class, SStartDisablePacket::encode, SStartDisablePacket::decode, SStartDisablePacket::handle);
/* 271 */     WyNetwork.registerPacket(SStopDisablePacket.class, SStopDisablePacket::encode, SStopDisablePacket::decode, SStopDisablePacket::handle);
/* 272 */     WyNetwork.registerPacket(SSetPoolInUsePacket.class, SSetPoolInUsePacket::encode, SSetPoolInUsePacket::decode, SSetPoolInUsePacket::handle);
/* 273 */     WyNetwork.registerPacket(SSetStacksPacket.class, SSetStacksPacket::encode, SSetStacksPacket::decode, SSetStacksPacket::handle);
/* 274 */     WyNetwork.registerPacket(SSetOverlayLayersPacket.class, SSetOverlayLayersPacket::encode, SSetOverlayLayersPacket::decode, SSetOverlayLayersPacket::handle);
/* 275 */     WyNetwork.registerPacket(SSetPauseTickPacket.class, SSetPauseTickPacket::encode, SSetPauseTickPacket::decode, SSetPauseTickPacket::handle);
/* 276 */     WyNetwork.registerPacket(SChangeAbilityAltModePacket.class, SChangeAbilityAltModePacket::encode, SChangeAbilityAltModePacket::decode, SChangeAbilityAltModePacket::handle);
/* 277 */     WyNetwork.registerPacket(SChangeAbilitySwitchModePacket.class, SChangeAbilitySwitchModePacket::encode, SChangeAbilitySwitchModePacket::decode, SChangeAbilitySwitchModePacket::handle);
/* 278 */     WyNetwork.registerPacket(SSwingTriggerPacket.class, SSwingTriggerPacket::encode, SSwingTriggerPacket::decode, SSwingTriggerPacket::handle);
/* 279 */     WyNetwork.registerPacket(SChangeMorphPacket.class, SChangeMorphPacket::encode, SChangeMorphPacket::decode, SChangeMorphPacket::handle);
/* 280 */     WyNetwork.registerPacket(SBonusManagerUpdatePacket.class, SBonusManagerUpdatePacket::encode, SBonusManagerUpdatePacket::decode, SBonusManagerUpdatePacket::handle);
/* 281 */     WyNetwork.registerPacket(SChangeAnimationStatePacket.class, SChangeAnimationStatePacket::encode, SChangeAnimationStatePacket::decode, SChangeAnimationStatePacket::handle);
/* 282 */     WyNetwork.registerPacket(SForceStopChargingPacket.class, SForceStopChargingPacket::encode, SForceStopChargingPacket::decode, SForceStopChargingPacket::handle);
/* 283 */     WyNetwork.registerPacket(SSetContinuityThresholdPacket.class, SSetContinuityThresholdPacket::encode, SSetContinuityThresholdPacket::decode, SSetContinuityThresholdPacket::handle);
/*     */   }
/*     */ }


/* Location:              C:\Users\herrc\Downloads\mine-mine-no-mi-1.16.5-0.10.8.jar!\xyz\pixelatedw\mineminenomi\init\ModNetwork.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.1.3
 */